### ISSUE TITLE
coap + tcp TcpThroughputClient can not run rightly

### ISSUE THREAD

**Issue by jiangyoudi** [eclipse/californium#1017]
Hi,I am sorry to trouble you.When I use TcpThroughputClient and TcpThroughputServer to test tcp connection(californium-2.0.0-M15),I meet this trouble:

Exception in thread "main" java.lang.IllegalStateException: URI scheme coap+tcp requires a previous set connector!
	at org.eclipse.californium.core.network.EndpointManager.getDefaultEndpoint(EndpointManager.java:132)
	at org.eclipse.californium.core.CoapClient.getEffectiveEndpoint(CoapClient.java:1266)
	at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1067)
	at org.eclipse.californium.core.CoapClient.put(CoapClient.java:713)
	at org.eclipse.californium.benchmark.TcpThroughputClient.main(TcpThroughputClient.java:32)

I do not know how to slove the problem and hope to get your help.thanks.

**Comment by boaks** [comment]
If possible, please retest with the fix in PR#1018

**Comment by jiangyoudi** [comment]
thanks,it works.
