### ISSUE TITLE
CoapServer produces orphaned ThreadPools

### ISSUE THREAD

**Issue by heikobornholdt** [eclipse/californium#1031]
I am using Californium version 1.0.7 and have noticed that `CoapServer` is producing orphaned Thread Pools.
I noticed this while running my unit tests. There I start and stop many Coap Servers. But the tests fail at some point because the system resources are exhausted as no new Thread Pools can be created anymore.

Here is a minimal example:
```java
package city.sane.wot.examples;

import org.eclipse.californium.core.CoapServer;

public class OrphanedThreadPools {
    public static void main(String[] args) throws InterruptedException {
        while (true) {
            CoapServer server = new CoapServer();
            server.start();
            server.stop();

            Thread.sleep(100L);
        }
    }
}
```
As a workaround you can call `server.setExecutor(null);` after stopping the server. This will shut down the ThreadPool.

Log:
```java
[19.865s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Exception in thread "main" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:803)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705)
	at org.eclipse.californium.core.network.CoapEndpoint.runInProtocolStage(CoapEndpoint.java:718)
	at org.eclipse.californium.core.network.CoapEndpoint.startExecutor(CoapEndpoint.java:283)
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:266)
	at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
	at city.sane.wot.examples.OrphanedThreadPools.main(OrphanedThreadPools.java:9)
[29.869s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Aug. 10, 2019 11:41:12 VORM. org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm run
WARNING: Exception while scheduling Mark-and-Sweep algorithm
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:803)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:152)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.run(SweepDeduplicator.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[39.872s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Aug. 10, 2019 11:41:22 VORM. org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm run
WARNING: Exception while scheduling Mark-and-Sweep algorithm
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:803)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:152)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.run(SweepDeduplicator.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

VisualVM graph:
![Bildschirmfoto 2019-08-10 um 11 43 04](https://user-images.githubusercontent.com/789788/62820399-20078c00-bb64-11e9-8d28-781ce72ef14b.png)

As a workaround, you can call `server.setExecutor(null);` after stopping the server. This will shut down the ThreadPool.

The problem also occurs in version 2.0.0-M16.

**Comment by boaks** [comment]
May be you give `CoapServer.destroy()` a chance.

**Comment by heikobornholdt** [comment]
Thanks, that solved my problem.
