### ISSUE TITLE
java.io.IOException: java.lang.IllegalStateException: automatic message IDs exhausted

### ISSUE THREAD

**Issue by StephenMhYt** [eclipse/californium#1051]
# Please providing basic issue information
When I run CoapClient to get CoapResponse in the multi-Threads,about 200 threads,client occurs the error.

Caused by: java.lang.IllegalStateException: automatic message IDs exhausted
	at org.eclipse.californium.core.network.UdpMatcher.sendRequest(UdpMatcher.java:137)
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:682)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:227)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:108)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendRequest(BlockwiseLayer.java:319)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
	at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendRequest(ExchangeCleanupLayer.java:62)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendRequest(BaseCoapStack.java:184)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendRequest(BaseCoapStack.java:86)
	at org.eclipse.californium.core.network.CoapEndpoint$4.run(CoapEndpoint.java:558)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:277)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

**Comment by StephenMhYt** [comment]
my californium version is 2.0.0-M16

**Comment by boaks** [comment]
I'm always a little curious about starting with benchmarks and load tests instead of exploring the normal function :-). 

So, I'm right that you try to benchmark a load test? If so, check issue #916.

**Comment by StephenMhYt** [comment]
Really appreciate your reply!

I just wander the coap based on UDP, and the other protocol based on TCP, how much the coap will be better? 
In service mesh structure, they change one-to-one transfer to multi-transfer between service and proxy(sidecar), so whether can we change to the coap for improving the performance?

**Comment by boaks** [comment]
> I just wander the coap based on UDP, and the other protocol based on TCP, how much the coap will be better?

I guess, you intended communication will not comply to N-START-1, means for 1 client, that this client waits with the next request until it receives the response. With that, coap scales with the number of clients (and so the overall messages), and not with the number of messages per client. The number of messages per client is limited by the range of the MID (65000) and the time the MID must stay unique, called exchange lifetime (default 246 seconds). If you just want to have a good guess for a UDP based protocol, you may lower the `EXCHANGE_LIFETIME` in `Californium.properties` from 247000 to a smaller value. How long does it take for you to get the message above? 15 s? Then I would go for 10000 ms (=> 10s). That would disable some stuff in CoAP (e.g. deduplication may sometimes not work).

**Comment by StephenMhYt** [comment]
>The number of messages per client is limited by the range of the MID (65000) and the time the MID must stay unique, called exchange lifetime (default 246 seconds).

Why will limit the number of messages per client? and what's the purpose of designing the `EXCHANGE_LIFETIME`?

**Comment by boaks** [comment]
> Why will limit the number of messages per client? 

The intention of CoAP RFC 7252 is to have a simple, robust and reliable protocol for embedded devices. To verify the "transmission" layer, messages are using a temporary unique MID. The size is defined to 16 Bit and the default time is defined by the maximum number of message retransmissions (including a increased backoff time) and a assumed maximum processing time. That accumulates to 247s.

Read [CoAP - Message Transmission](https://tools.ietf.org/html/rfc7252#section-4) for further information.

> and what's the purpose of designing the EXCHANGE_LIFETIME?

Reducing these 247s limit the time, where the MIDs are considered to be unique. For first experiments, it's a good trick to gather more messages throughput. But for production it may come with some drawbacks. So first check, if this trick helps you at all.
   
Generally, my impression is that, you consider CoAP to be a universal  UDP based protocol. But, as I wrote above, it's a protocol, which's intention is to support simple embedded implementations.
