### ISSUE TITLE
Error when connecting to Tradfri gateway

### ISSUE THREAD

**Issue by thstieler** [eclipse/californium#1061]
Hello,

I'm currently trying to establish a connection to an Ikea Tradfri gateway with Eclipse Californium library (version 2.0.0-M16), but unfortunately already the first request fails with a BAD_RECORD_MAC fatal alert.

I reviewed some similar implementations using Califorium, for example the Tradfri support from the Eclipse Smarthome project, and as far as I understood, at first I have to get a new preshared key by posting the gateway security code to the gateway.

My code looks like that:

```java
     private static void obtainIdentityAndPreSharedKey(String address, int port, String securityCode) throws Exception {
        final DtlsConnectorConfig dtlsConnectorConfig = new DtlsConnectorConfig.Builder()
                .setAddress(new InetSocketAddress(0))
                .setPskStore(new StaticPskStore("Client_identity", psk.getBytes())).build();
        final DTLSConnector dtlsConnector = new DTLSConnector(dtlsConnectorConfig);

        final CoapEndpoint authEndpoint = new CoapEndpoint.Builder().setConnector(dtlsConnector)
                .setNetworkConfig(NetworkConfig.createStandardWithoutFile()).build();

        final CoapClient deviceClient = new CoapClient(new URI("coaps://" + address + ":" + port + "/15011/9063"));
        deviceClient.setEndpoint(authEndpoint);

        final String identity = UUID.randomUUID().toString().replace("-", "");
        final JSONObject json = new JSONObject().append("9090", identity);

        LOG.info("Request payload: {}", json.toString());
        final CoapResponse gatewayResponse = deviceClient.post(json.toString(), MediaTypeRegistry.APPLICATION_JSON);

        [...]
    }
```

The post call fails with a HandshakeException:

```
Caused by: org.eclipse.californium.scandium.dtls.HandshakeException: Received 'fatal alert'
        at org.eclipse.californium.scandium.DTLSConnector.processAlertRecord(DTLSConnector.java:1317) ~[scandium-2.0.0-M16.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1103) ~[scandium-2.0.0-M16.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector.access$300(DTLSConnector.java:214) ~[scandium-2.0.0-M16.jar!/:na]
        at org.eclipse.californium.scandium.DTLSConnector$10.run(DTLSConnector.java:1027) ~[scandium-2.0.0-M16.jar!/:na]
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:277) ~[element-connector-2.0.0-M16.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
```

The trace logs are looking like that:

```
2019-09-04 16:06:45.665 DEBUG 28124 --- [ction-Handler-5] o.e.californium.scandium.DTLSConnector   : Sending flight of 3 message(s) to peer [/192.168.178.38:5684] using 1 datagram(s) of max. 1500 bytes
2019-09-04 16:06:45.665 DEBUG 28124 --- [ction-Handler-5] o.e.c.scandium.dtls.ClientHandshaker     : Processed SERVER_HELLO_DONE (14) message with sequence no [2] from peer [/192.168.178.38:5684]
2019-09-04 16:06:45.665 DEBUG 28124 --- [ction-Handler-5] o.e.c.scandium.dtls.DTLSSession          : Updated receive window with sequence number [2]: new upper boundary [63], new bit vector [111]
2019-09-04 16:06:45.667 DEBUG 28124 --- [0/0.0.0.0:50307] o.e.californium.scandium.DTLSConnector   : Received 1 DTLS records from /192.168.178.38:5684 using a 16490 byte datagram buffer
2019-09-04 16:06:45.667 TRACE 28124 --- [0/0.0.0.0:50307] o.e.californium.scandium.DTLSConnector   : connection available for /192.168.178.38:5684,null
2019-09-04 16:06:45.668 TRACE 28124 --- [ction-Handler-6] o.e.californium.scandium.DTLSConnector   : Received DTLS record of type [Alert (21)], length: 2, [epoche:0,reqn:3]
2019-09-04 16:06:45.668 TRACE 28124 --- [ction-Handler-6] o.e.californium.scandium.dtls.Record     : Decrypting record fragment using current read state
DTLSConnectionState:
        Cipher suite: TLS_NULL_WITH_NULL_NULL
        Compression method: NULL
        IV: null
        MAC key: null
        Encryption key: null
2019-09-04 16:06:45.669 TRACE 28124 --- [ction-Handler-6] o.e.californium.scandium.DTLSConnector   : Processing FATAL ALERT from [/192.168.178.38:5684]: BAD_RECORD_MAC
2019-09-04 16:06:45.670 TRACE 28124 --- [ction-Handler-6] o.e.c.s.dtls.InMemoryConnectionStore     : connection: remove dtls-con: CID=96B1E88671, /192.168.178.38:5684, ongoing handshake (size 0, left jobs: 0)
    [...]
```

I tried many different variants, without success.

As last resort, I tried my luck with the cf-commandline tool. I cloned git project https://github.com/eclipse/californium.tools.git and build it for version 2.0.0-M16. Then I started the client:

 ```
   java -jar cf-client-2.0.0-M16.jar -psk GET coaps://192.168.178.38:5684/15001
```

And guess what: Same problem :-(!

```
16:11:00.529 DEBUG [DTLSConnector]: Sending flight of 3 message(s) to peer [/192.168.178.38:5684] using 1 datagram(s) of max. 1500 bytes
16:11:00.529 DEBUG [ClientHandshaker]: Processed SERVER_HELLO_DONE (14) message with sequence no [2] from peer [/192.168.178.38:5684]
16:11:00.529 DEBUG [DTLSSession]: Updated receive window with sequence number [1]: new upper boundary [63], new bit vector [111]
16:11:00.531 DEBUG [DTLSConnector]: Received 1 DTLS records from /192.168.178.38:5684 using a 16490 byte datagram buffer
16:11:00.531 TRACE [DTLSConnector]: connection available for /192.168.178.38:5684,null
16:11:00.531 TRACE [DTLSConnector]: Received DTLS record of type [Alert (21)], length: 2, [epoche:0,reqn:3]
16:11:00.531 TRACE [Record]: Decrypting record fragment using current read state
DTLSConnectionState:
        Cipher suite: TLS_NULL_WITH_NULL_NULL
        Compression method: NULL
        IV: null
        MAC key: null
        Encryption key: null
16:11:00.532 TRACE [DTLSConnector]: Processing FATAL ALERT from [/192.168.178.38:5684]: BAD_RECORD_MAC
16:11:00.532 TRACE [InMemoryConnectionStore]: connection: remove dtls-con: CID=A4056893F8, /192.168.178.38:5684, ongoing handshake (size 0, left jobs: 0)
    [...]
```
As the californium command line client has the same problem, maybe it's not a problem with my code, but a general interoperability problem between Ikea Tradfri gateway and Eclipse Californium/Scandium?

Any help or comment is appreciated!

**Comment by boaks** [comment]
PSK is a secure "username/password", where the password is not exchanged but used to check, if the other peer has the same password. Therefore the username is called "identity" and the password is the "secret". 
Therefore:
first, use the right name as identity.
second, use the right secret.
The culprit of many issues with that is, that the secret could be any binary value. Therefore, it's important, that you known, if the secret is, for example, provided in hexadecimal. Then you must decode that and provide the bytes.

**Comment by thstieler** [comment]
Well, I hope and think I did that.

I reviews and (mostly) reimplemented the method obtainIdentityAndPreSharedKey() in that class:
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java

The identity for this call is `Client_identity`, if I use another string, I get another error: 
```
2019-09-04 17:47:33.152 TRACE 17485 --- [ction-Handler-6] o.e.californium.scandium.DTLSConnector   : Processing FATAL ALERT from [/192.168.178.38:5684]: UNKNOWN_PSK_IDENTITY
```
So I hope that `Client_identity` is fine.

The code is the text (definitely not HEX) found on the gateway label, converted to bytes, so I hope this is ok as well.

Any idea how to get more details about problem?

**Comment by thstieler** [comment]
ARRRGGG!

I tried some variant of ambiguous letters within the security code.
I and l are different letters, now I have a different code which gives me a different result.

Actually it's not yet working, but I have a starting point for further investigations...

Thanks for help and sorry for any unnecessary work :-(...

**Comment by boaks** [comment]
I checked it with my tradfri and 2.0.0-M16 works.
The secret is ASCII, so that should not be an issue.

"Client_identity" is in the meantime only for the user management.
With that you create a user, which then must be used for the other functions.

```
public void createUser(String username) throws ConnectorException, IOException {
	client.setURI(SERVER_URI + "15011/9063");
	CoapResponse response = client.post("{\"9090\":\"" + username + "\"}",
			MediaTypeRegistry.APPLICATION_JSON);
	System.out.println(Utils.prettyPrint(response));
}
```
To create a user. The response will contain the secret, which, used with the new username, allows to use the other functions.

**Comment by thstieler** [comment]
After some more refactorings, the communication with the Tradfri gateway is finally working!
