### ISSUE TITLE
can not run multicast server demo in Mac OS

### ISSUE THREAD

**Issue by RaymondMcGuire** [eclipse/californium#1170]
I can't run the multicast demo in Mac, but in windows is ok..

the following is the log info:

[main] INFO org.eclipse.californium.core.network.config.NetworkConfig - loading properties from file /Users/raymondmg/Project/CoapSimulate/coap_server/Californium.properties
[main] INFO org.eclipse.californium.core.network.RandomTokenGenerator - using tokens of 8 bytes in length

[main] INFO org.eclipse.californium.core.network.CoapEndpoint - coap CoapEndpoint uses udp plain

[main] INFO org.eclipse.californium.core.network.stack.BlockwiseLayer - BlockwiseLayer uses MAX_MESSAGE_SIZE=1024, PREFERRED_BLOCK_SIZE=512, BLOCKWISE_STATUS_LIFETIME=300000, MAX_RESOURCE_BODY_SIZE=8192, BLOCKWISE_STRICT_BLOCK2_OPTION=false

[main] INFO org.eclipse.californium.core.network.stack.ReliabilityLayer - ReliabilityLayer uses ACK_TIMEOUT=2000, ACK_RANDOM_FACTOR=1.5, and ACK_TIMEOUT_SCALE=2.0 as default
[main] INFO org.eclipse.californium.core.CoapServer - Starting server
coap server: 70

[main] INFO org.eclipse.californium.core.network.CoapEndpoint - coap Stopping endpoint at coap://0.0.0.0:5683

[main] ERROR org.eclipse.californium.core.CoapServer - cannot start server endpoint [0.0.0.0/0.0.0.0:5683]

java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at org.eclipse.californium.elements.UdpMulticastConnector.start(UdpMulticastConnector.java:89)
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:506)
	at org.eclipse.californium.core.CoapServer.start(CoapServer.java:252)
	at coap_server.CoapMultiCastServer.main(CoapMultiCastServer.java:30)
Exception in thread "main" java.lang.IllegalStateException: None of the server endpoints could be started
	at org.eclipse.californium.core.CoapServer.start(CoapServer.java:260)
	at coap_server.CoapMultiCastServer.main(CoapMultiCastServer.java:30)

**Comment by boaks** [comment]
Please check, if issue #872 works for as well.

**Comment by RaymondMcGuire** [comment]
> Please check, if issue #872 works for you as well.

Thank you for your help.
I found the reason is that "IPv6 address being returned `fromjava.net.NetworkInterface.getDefault()`".

So start the JVM with `-Djava.net.preferIPv4Stack=true` can solve this problem, the multicast server demo has no problem.

If someone has a similar problem, please check the following link:
[stackoverflow](https://stackoverflow.com/questions/18747134/getting-cant-assign-requested-address-java-net-socketexception-using-ehcache)

**Comment by boaks** [comment]
I improved the multicast support for IPv6, see PR #1171 .
If possible, please check, if with that PR the multicast example works with IPv6 only.
