### ISSUE TITLE
NPE on Request.setDestinationContext()

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1234]
I get this NPE : 
```
java.lang.NullPointerException: null
	at org.eclipse.californium.core.coap.Request.setDestinationContext(Request.java:888)
	at org.eclipse.leshan.client.californium.request.CoapRequestBuilder.buildRequestSettings(CoapRequestBuilder.java:125)
	at org.eclipse.leshan.client.californium.request.CoapRequestBuilder.visit(CoapRequestBuilder.java:45)
	at org.eclipse.leshan.core.request.BootstrapRequest.accept(BootstrapRequest.java:41)
	at org.eclipse.leshan.client.californium.request.CaliforniumLwM2mRequestSender.send(CaliforniumLwM2mRequestSender.java:63)
```
This happened because my inetsocketaddress can probably not resolve the hostname as I lost all my network connections.  

I'm not sure if this is an intended behavior. :thinking: 
My first intuition was that I should not get an NPE when I just set the context ? 
@boaks WDYT ?

**Comment by boaks** [comment]
I'm not sure, what exactly is `null`. Did you investigate it?

**Comment by sbernard31** [comment]
I'm pretty sure this is :  `peerContext.getPeerAddress().getAddress()`

**Comment by boaks** [comment]
Do you pass in a `AddressEndpointContext` or your own implementation?
The `AddressEndpointContext` checks for `null`. So I'm not sure, if, when we tolerate it in the Request, it causes something else. Or do you think, just replace the exception by illegalargumentexception?

**Comment by boaks** [comment]
> I'm pretty sure this is : peerContext.getPeerAddress().getAddress()

OK, we can add a check for resolved and see what happens.

**Comment by sbernard31** [comment]
I pass a `AddressEndpointContext`.
In `Request`, it seems we check that `InetSocketAddress` is not null but not `InetSocketAddress.getAddress()`

Ideally, I would like no error about address/hostname resolution at configuration time  but only at sending time. 
I think this was like this before the multicast addition.  

Maybe this is a silly requirement but it seems to me this makes the error handling simple, because no error at config and this will failed later at sending in a more elegant way : 
 ```
org.eclipse.leshan.core.request.exception.SendFailedException: Request CON-POST   MID=30945, Token=9890FB1F3446AF73, OptionSet={"Uri-Path":"rd", "Content-Format":"application/link-format", "Uri-Query":["b=UQ","lwm2m=1.0","lt=630720000","ep=LESHAN00000004"]}, Network is unreachable"</>;rt="oma.lwm2m",</1/0".. 39 bytes cannot be sent
	at org.eclipse.leshan.core.californium.CoapSyncRequestObserver.onSendError(CoapSyncRequestObserver.java:97)
	at org.eclipse.californium.core.coap.Message.setSendError(Message.java:896)
	at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1122)
	at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1244)
	at org.eclipse.californium.elements.RawData.onError(RawData.java:303)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:2307)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessageWithSession(DTLSConnector.java:2284)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:2144)
	at org.eclipse.californium.scandium.DTLSConnector.access$1600(DTLSConnector.java:217)
	at org.eclipse.californium.scandium.DTLSConnector$14.run(DTLSConnector.java:2060)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Network is unreachable
	at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at org.eclipse.californium.scandium.DTLSConnector.sendNextDatagramOverNetwork(DTLSConnector.java:2431)
	at org.eclipse.californium.scandium.DTLSConnector.sendRecord(DTLSConnector.java:2424)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:2303)
	... 11 common frames omitted
 ```

Maybe removing the multicast attribute and make a dynamic implementation of  `isMulticast` would be better ?

**Comment by boaks** [comment]
FMPOV, just add a check 

```
multicast = peerContext != null && !peerContext.getPeerAddress().isUnresolved()
	&& peerContext.getPeerAddress().getAddress().isMulticastAddress();
```
