### ISSUE TITLE
Client side X509 Cert Authentication

### ISSUE THREAD

**Issue by BitFis** [eclipse/californium#1348]
Dear Californium Team

I was trying to setup a client side authentication using californium version `2.3.0` on server and client. Am I configuring
something wrong or is it currently not supported to authenticate the client with a X509 certificate?
Using `DTLS_ECDHE_ECDSA_WITH_AES_128_CCM_8` cipher with ECDSA Certificates. I was able to connect to the server with mbedtls successfully, so the server side seems to work. [Here the wireshark dump file](https://github.com/eclipse/californium/files/4824438/wireshark_dump.pcapng.txt) (pcap format).

Client confiugration:
```java
client = new CoapClient("coaps://[::1]/secure");

DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();

clientCerts = new Credentials("test_credentials.p12", "device", "password");

List<CertificateType> types = new ArrayList<>();
types.add(CertificateType.X_509);

builder.setClientOnly();
builder.setIdentity(clientCerts.getPrivateKey(), clientCerts.getCertificateChain(), types);

builder.setTrustStore(TrustCerts);
builder.setSupportedCipherSuites(CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8);

client.setEndpoint(new CoapEndpoint.Builder().setConnector(new DTLSConnector(builder.build())).build());

client.get()
```

<details>
  <summary>Server Log</summary>
  
```bash
    815 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#8] DEBUG org.eclipse.californium.scandium.dtls.CertificateMessage  - created CERTIFICATE message with truncated certificate chain [length: 0]
    820 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#8] DEBUG org.eclipse.californium.scandium.dtls.DTLSSession  - Setting maximum fragment length for peer [/0:0:0:0:0:0:0:1:5684] to 1395 bytes
    831 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#8] DEBUG org.eclipse.californium.scandium.dtls.ClientHandshaker  - Processed SERVER_HELLO_DONE (14) message from peer [/0:0:0:0:0:0:0:1:5684]
    831 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#8] DEBUG org.eclipse.californium.scandium.dtls.DTLSSession  - Updated receive window with sequence number [5]: new upper boundary [5], new bit vector [111111]
    831 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.CertificateMessage  - Parsing X.509 CERTIFICATE message
    832 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.ServerHandshaker  - response for flight 4 started
    832 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.ServerHandshaker  - Processing CERTIFICATE (11) message from peer [/0:0:0:0:0:0:0:1:47169], seqn: [2]
    832 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.ServerHandshaker  - Client authentication failed: missing certificate!
    834 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.DTLSConnector  - Aborting handshake with peer [/0:0:0:0:0:0:0:1:47169]: Client Certificate required!
    835 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.InMemoryConnectionStore  - connection: remove dtls-con: CID=2BF24D28C59A, /0:0:0:0:0:0:0:1:47169, ongoing handshake 78ABAD10AD52 (size 0, left jobs: 4)
    835 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#9] DEBUG org.eclipse.californium.scandium.dtls.InMemoryConnectionStore  - connection: remove dtls-con: CID=6F1C4E23FC00, /0:0:0:0:0:0:0:1:5684, ongoing handshake 78ABAD10AD52 (size 0)
    842 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.ServerHandshaker  - handshake failed dtls-con: CID=2BF24D28C59A
    org.eclipse.californium.scandium.dtls.HandshakeException: Client Certificate required!
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.receivedClientCertificate(ServerHandshaker.java:310)
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.doProcessMessage(ServerHandshaker.java:232)
        at org.eclipse.californium.scandium.dtls.Handshaker.processNextMessages(Handshaker.java:694)
        at org.eclipse.californium.scandium.dtls.Handshaker.processMessage(Handshaker.java:585)
        at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:1649)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1336)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
    843 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#9] DEBUG org.eclipse.californium.scandium.dtls.ClientHandshaker  - handshake failed dtls-con: CID=6F1C4E23FC00
    org.eclipse.californium.scandium.dtls.HandshakeException: Received 'fatal alert'
        at org.eclipse.californium.scandium.DTLSConnector.processAlertRecord(DTLSConnector.java:1580)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1330)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
    844 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#9] DEBUG org.eclipse.californium.scandium.dtls.Connection  - Handshake with [/0:0:0:0:0:0:0:1:5684] has failed
    844 [DTLS-Worker-0.0.0.0/0.0.0.0:47169#9] DEBUG org.eclipse.californium.scandium.DTLSConnector  - Handshake with [/0:0:0:0:0:0:0:1:5684] failed, report error to deferred 1 messages
    843 [DTLS-Worker-0.0.0.0/0.0.0.0:5684#5] DEBUG org.eclipse.californium.scandium.dtls.Connection  - Handshake with [/0:0:0:0:0:0:0:1:47169] has failed
```
</details>

**Comment by boaks** [comment]
The wireshark log shows, that your client provides a empty CERTIFICATE message.

I'm not sure, 

```
clientCerts = new Credentials("test_credentials.p12", "device", "password");
```

where this `Credentials` is from, and what the "test_credentials.p12" contains.

**Comment by boaks** [comment]
> Am I configuring something wrong or is it currently not supported to authenticate the client with a X509 certificate?

x509 client authentication is supported (ECDSA).

if possible, please also provide the californium client log.

**Comment by BitFis** [comment]
That was it, thank you.
