### ISSUE TITLE
"Address changed" instead of "certificates do not form a chain"

### ISSUE THREAD

**Issue by sverhagen** [eclipse/californium#1398]
Using version 2.3 of Californium. Thank you for this library.

I'm using the following code in a test, with **a certificate that the server cannot validate**:

    DtlsConnectorConfig connectorConfig = new DtlsConnectorConfig.Builder()
            .setClientOnly()
            .setIdentity(privateKey, /* unknown: */ certificates, CertificateType.X_509)
            .setRecommendedCipherSuitesOnly(false)
            .setSniEnabled(false)
            .setTrustStore(secretsHelper.getCertificates())
            .build();

    CoapEndpoint endpoint = new CoapEndpoint.Builder()
            .setConnector(new DTLSConnector(connectorConfig)).build();

    new CoapClient(format("coaps://localhost:%d/some_endpoint", serverPort))
            .setEndpoint(endpoint)
            .post("{}", MediaTypeRegistry.APPLICATION_JSON);

Because the server cannot validate the certificate, I am expecting an exception. When running this, I am seeing the following exception in the log file. It is a good exception, what I expect:

    java.lang.IllegalArgumentException: Given certificates do not form a chain
        at org.eclipse.californium.elements.util.CertPathUtil.generateCertPath(CertPathUtil.java:224)
        at org.eclipse.californium.elements.util.CertPathUtil.generateValidatableCertPath(CertPathUtil.java:292)
        at org.eclipse.californium.scandium.dtls.CertificateMessage.<init>(CertificateMessage.java:142)
        at org.eclipse.californium.scandium.dtls.ClientHandshaker.createCertificateMessage(ClientHandshaker.java:613)
        at org.eclipse.californium.scandium.dtls.ClientHandshaker.processMasterSecret(ClientHandshaker.java:517)
        at org.eclipse.californium.scandium.dtls.ClientHandshaker.receivedServerHelloDone(ClientHandshaker.java:468)
        at org.eclipse.californium.scandium.dtls.ClientHandshaker.doProcessMessage(ClientHandshaker.java:250)
        at org.eclipse.californium.scandium.dtls.Handshaker.processNextMessages(Handshaker.java:694)
        at org.eclipse.californium.scandium.dtls.Handshaker.processMessage(Handshaker.java:585)
        at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:1649)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1336)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

However, this is not the exception that I'm getting thrown, rather this one:

    java.io.IOException: java.io.IOException: address changed!

        at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1120)
        at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1092)
        at org.eclipse.californium.core.CoapClient.post(CoapClient.java:561)
        at io.skyward.services.conduit.service.SigningCertificatesIntegrationTest.testConduitTraffic(SigningCertificatesIntegrationTest.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
        at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
        at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
        at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
        at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
    Caused by: java.io.IOException: address changed!
        at org.eclipse.californium.scandium.dtls.Connection.updatePeerAddress(Connection.java:299)
        at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.removeFromAddressConnections(InMemoryConnectionStore.java:566)
        at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.remove(InMemoryConnectionStore.java:541)
        at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.remove(InMemoryConnectionStore.java:523)
        at org.eclipse.californium.scandium.DTLSConnector.terminateConnection(DTLSConnector.java:1463)
        at org.eclipse.californium.scandium.DTLSConnector.terminateConnection(DTLSConnector.java:1423)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1348)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1195)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

It seems like #955 is dealing with this issue, but it should have been resolved. I am not finding much else. Maybe I am doing this wrong, but it seems like this is the wrong exception. Bug or user error? Thanks for your help!

**Comment by boaks** [comment]
Thanks for reporting.
The error detection in handshake got complicate over the time.
The "address changed" is the case, when the connection is removed without prior setting a cause.
 I will try to reproduce it and fix the reported error.

**Comment by boaks** [comment]
Please retest with PR #1400

**Comment by boaks** [comment]
Just to mention:
Scandium detects that certificate failure before it sends the certificate message.
So the server is not tested with that. Currently I consider to fail earlier in the `DtlsConnectorConfig`. 
Do you have other means/tools to validate the servers behaviour?

**Comment by sverhagen** [comment]
After submitting this issue, I spent some more nightly hours and got more clarity.

>Scandium detects that certificate failure before it sends the certificate message.

Yes, I _thought_ that I was giving the client certificates that the _server_ couldn't validate, but instead I was giving the client a certificate and a mismatched parent certificate. I misinterpreted the exception: `Given certificates do not form a chain`.

I think it nonetheless is a valid issue that it says `address changed!` instead. And you fixed this in the `bosch-io:fix_reported_handshake_error`, it now says:

    java.io.IOException: org.eclipse.californium.scandium.dtls.HandshakeException: Cannot process handshake message, caused by Given certificates do not form a chain

Fixed! :heavy_check_mark: 

Thank you.

---

>Do you have other means/tools to validate the servers behaviour?

I think so. When configuring the client-side correctly to have a certificate and a **matching** parent certificate **that the server cannot validate**, I'm now getting the following error:

    org.eclipse.californium.scandium.dtls.HandshakeException: Received 'fatal alert'

Relative to a complete happy path, the `fatal alert` is useful, but it is also not very informative for what is going on. I assumed this may just be how the protocol works (i.e. now way to hear back the detailed error message from the server), but that's just my ignorant assumption.

**Comment by boaks** [comment]
> I assumed this may just be how the protocol works (i.e. now way to hear back the detailed error message from the server),

AFAIK, (D)TLS defines more fine grained alerts, [RFC5246, 7.2.  Alert Protocol](https://tools.ietf.org/html/rfc5246#section-7.2). There have been a couple of discussion, what should reported and not.
Actually, I just didn't spend enough time in clean that up. For me that is "postponed" after a future redesign, when the ip-addresses will be removed from the inner scandium methods. I hope afterwards, the methods a stable enough to so that the alert and termination cleanup will pay off.

There is still much to do :-)

**Comment by sverhagen** [comment]
Yes, I think this can be closed, thank you!
