### ISSUE TITLE
IPv6 processing

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#164]
Using  `InetSocketAddress.getHostString()` causes errors, when used for creating new InetSocketAddress.

Example:

     coap+tcp://0:0:0:0:0:0:0:0:5683

and using that as (leshan example):

        this.registrationEndpointUri = registrationEndpointUri;
        this.registrationEndpointAddress = new InetSocketAddress(registrationEndpointUri.getHost(), registrationEndpointUri.getPort());

results in:

    java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[?:1.8.0_51]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216) ~[?:1.8.0_51]

**Comment by tuncagurkan** [comment]
Hi @boaks ,
Did you fix this bug or find any solution to use ipv6 host instead of InetSocketAddress? If yes, please share with us.

Thanks with advance,
Tunca

**Comment by boaks** [comment]
There may be many issues caused by using `InetSocketAddress.getHostString()` with IPv6.
But the issue above is related to `Endpoint.getUri()`, and there it is fixed.

Extracted from the startup of the cf-plugtest-server:

> listen on coap://192.168.122.1:5683
> listen on coaps://192.168.122.1:5684
> listen on coap://[fd00:0:0:0:9df3:7e2:99ad:48a6]:5683
> listen on coaps://[fd00:0:0:0:9df3:7e2:99ad:48a6]:5684

So the IPv6 raw-address is now enclosed in "[...]", as required for IPv6.

Do you have a actual issue with IPv6?
