### ISSUE TITLE
NullPointerException when sending RST as response.

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#166]
Tcp/UdpMatcher / ExchangeObserverImpl / completed :

    java.lang.NullPointerException
	at org.eclipse.californium.core.network.UdpMatcher$ExchangeObserverImpl.completed(UdpMatcher.java:463)
	at org.eclipse.californium.core.network.Exchange.setComplete(Exchange.java:451)
	at org.eclipse.californium.core.network.UdpMatcher.sendEmptyMessage(UdpMatcher.java:164)
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendEmptyMessage(CoapEndpoint.java:629)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendEmptyMessage(BaseCoapStack.java:194)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendEmptyMessage(AbstractLayer.java:83)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendEmptyMessage(AbstractLayer.java:83)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendEmptyMessage(AbstractLayer.java:83)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendEmptyMessage(AbstractLayer.java:83)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendEmptyMessage(AbstractLayer.java:83)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendEmptyMessage(BaseCoapStack.java:89)
	at org.eclipse.californium.core.network.CoapEndpoint.sendEmptyMessage(CoapEndpoint.java:521)
	at org.eclipse.californium.core.network.Exchange.sendReject(Exchange.java:196)
	at org.eclipse.californium.core.test.SmallServerClientTest$1.deliverRequest(SmallServerClientTest.java:124)

PR with fix will follow.

**Comment by boaks** [comment]
See #155
