### ISSUE TITLE
[coap-observe] deleteting an observed resource

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1754]
I'm using californium 3.0.0-M4.

My use case : I observe a resource but at some time the resource is deleted.

The RFC7641 says  :
> A notification SHOULD have a 2.05 (Content) or 2.03 (Valid) response
   code.  **However, in the event that the state of a resource changes in
   a way that would cause a normal GET request at that time to return a
   non-2.xx response (for example, when the resource is deleted), the
   server SHOULD notify the client by sending a notification with an
   appropriate response code (such as 4.04 Not Found) and subsequently
   MUST remove the associated entry from the list of observers of the
   resource.**
   
 In my case  when this happens I get this exception below and the 4.04 response is never sent.  : 
```
BaseCoapStack 2021-09-30 17:45:55,874 [WARN] error send response CON-4.04   MID=   -1, Token=BB7B530AF042FDD5, OptionSet={"Content-Format":"text/plain"}, canceled no payload
org.eclipse.californium.core.network.ExchangeCompleteException: Exchange[R48, complete] is already complete! CON-4.04   MID=   -1, Token=BB7B530AF042FDD5, OptionSet={"Content-Format":"text/plain"}, canceled no payload
	at org.eclipse.californium.core.network.Exchange.assertIncomplete(Exchange.java:1269)
	at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerWithMessageId(InMemoryMessageExchangeStore.java:239)
	at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerOutboundResponse(InMemoryMessageExchangeStore.java:412)
	at org.eclipse.californium.core.network.UdpMatcher.sendResponse(UdpMatcher.java:160)
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendResponse(CoapEndpoint.java:867)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendResponse(BaseCoapStack.java:236)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendResponse(ReliabilityLayer.java:130)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendResponse(BlockwiseLayer.java:697)
	at org.eclipse.californium.core.network.stack.ObserveLayer.sendResponse(ObserveLayer.java:120)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendResponse(AbstractLayer.java:74)
	at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendResponse(ExchangeCleanupLayer.java:87)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendResponse(BaseCoapStack.java:194)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendResponse(BaseCoapStack.java:110)
	at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:691)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

 ```

**Comment by boaks** [comment]
`exchange.retransmitResponse();` seems to be missing in that case. I will try to fix it (hope, next week).

**Comment by rogierc** [comment]
> That's strange because this seems different than what I face

At least Cf 2.6.5 does :wink:

```
INFO  2021-10-01 14:58:41,887 [CoapServer(main)#4] [processor: ; event: ] org.eclipse.californium.core.network.Exchange: Exchange[R6] store NON notification: KeyMID[127.0.0.1:37447-36345]
INFO  2021-10-01 14:58:41,888 [CoapServer(main)#4] [processor: ; event: ] org.eclipse.californium.core.network.interceptors.MessageTracer: UDP(127.0.0.1:37447) <== res NON-2.05   MID=36346, Token=57E0C60FC138F6CB, OptionSet={"ETag":0xaabb11, "Observe":19, "Content-Format":"text/plain", "Max-Age":10}, "HALLO DAAR"
INFO  2021-10-01 14:58:46,301 [CoapServer(main)#1] [processor: ; event: ] org.eclipse.californium.core.network.interceptors.MessageTracer: UDP(127.0.0.1:42151) ==> req CON-DELETE MID=13741, Token=2875C5779590E8EF, OptionSet={"Uri-Path":"observeer", "Accept":"text/plain"}, no payload
INFO  2021-10-01 14:58:46,303 [[MuleRuntime].uber.05: [test-coap-1].test-coap-1Flow6.CPU_LITE @15e222e] [processor: test-coap-1Flow6/processors/0; event: 5049b4d1-22b7-11ec-a885-9cb6d0e8576b] org.eclipse.californium.core.CoapResource: remove observe relation between 127.0.0.1:37447#57E0C60FC138F6CB and resource nullobserveer (Exchange[R6], size 0)
. . . 
INFO  2021-10-01 14:58:46,303 [CoapServer(main)#7] [processor: ; event: ] org.eclipse.californium.core.network.Exchange: Exchange[R6] store NON notification: KeyMID[127.0.0.1:37447-36346]
INFO  2021-10-01 14:58:46,304 [CoapServer(main)#5] [processor: ; event: ] org.eclipse.californium.core.network.interceptors.MessageTracer: UDP(127.0.0.1:42151) <== res ACK-2.02   MID=13741, Token=2875C5779590E8EF, OptionSet={}, no payload
INFO  2021-10-01 14:58:46,304 [CoapServer(main)#7] [processor: ; event: ] org.eclipse.californium.core.network.Exchange: Exchange[R6] removing NON notification: KeyMID[127.0.0.1:37447-36346]
INFO  2021-10-01 14:58:46,304 [CoapServer(main)#7] [processor: ; event: ] org.eclipse.californium.core.network.interceptors.MessageTracer: UDP(127.0.0.1:37447) <== res CON-4.04   MID=36347, Token=57E0C60FC138F6CB, OptionSet={}, no payload
INFO  2021-10-01 14:58:46,307 [CoapServer(main)#4] [processor: ; event: ] org.eclipse.californium.core.network.interceptors.MessageTracer: UDP(127.0.0.1:37447) ==> emp ACK        MID=36347

```

**Comment by boaks** [comment]
[ObserveRelation.cancel()](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/observe/ObserveRelation.java#L159) may execute the complete asynchronous. That may therefore  cause some unintended "race condition".

**Comment by rogierc** [comment]
When testing with Cf 3.0.0-SNAPSHOT:
```
19:18:43.366 INFO [MessageTracer]: UDP(127.0.0.1:41547) <== res ACK-4.04   MID=55093, Token=67D5CE57447F2630, OptionSet={}, no payload (o.e.c.c.n.i.MessageTracer.sendResponse:48)
```
An ACK instead of a CON seems to be sent now. Has this changed?

**Comment by boaks** [comment]
> An ACK instead of a CON seems to be sent now. Has this changed?

Not by intention.

A simple unit test added to ObserveTest:

```
	@Test
	public void testObserveClientDeleteResource() throws Exception {

		final AtomicInteger resetCounter = new AtomicInteger(0);

		serverEndpoint.addInterceptor(new ServerMessageInterceptor(resetCounter));
		resourceX.setObserveType(Type.NON);

		CoapClient client = new CoapClient(uriX);
		cleanup.add(client);
		CountingCoapHandler handler = new CountingCoapHandler();
		CoapObserveRelation rel = client.observeAndWait(handler);

		// onLoad is called asynchronous to returning the response
		// therefore wait for one onLoad
		assertTrue(handler.waitOnLoadCalls(1, 1000, TimeUnit.MILLISECONDS));

		assertFalse("Response not received", rel.isCanceled());
		assertNotNull("Response not received", rel.getCurrent());
		assertEquals("\"resX says hi for the 1 time\"", rel.getCurrent().getResponseText());

		resourceX.delete();

		assertTrue(handler.waitOnLoadCalls(2, 1000, TimeUnit.MILLISECONDS));

		CoapResponse coapResponse = handler.responses.get(1);
		assertEquals(CoAP.ResponseCode.NOT_FOUND, coapResponse.getCode());
		assertEquals(Type.CON, coapResponse.advanced().getType());
	}
```

shows that also a 2.6 uses the ACK (at least "on my machine"). And sure, that is an bug.
I guess, there will be a l lot of side effects on what exactly have been executed before.

**Comment by rogierc** [comment]
hm, logging in my comment shown above is produced by 3.6.5. It says: 
```
UDP(127.0.0.1:37447) <== res CON-4.04   MID=36347, Token=57E0C60FC138F6CB, OptionSet={}, no payload
```
>shows that also a 2.6 uses the ACK

puzzles me...

**Comment by boaks** [comment]
Hard to see, what happens "on your machine".
I guess, the processing in [ReliabilityLayer.sendResponse()](https://github.com/eclipse/californium/blob/2.6.x/californium-core/src/main/java/org/eclipse/californium/core/network/stack/ReliabilityLayer.java#L126-L140) is different. 

Using fix_observer_2_6 with (see PR #1758,  included there):

```
	<logger name="org.eclipse.californium.core.network.stack.ReliabilityLayer" level="TRACE" additivity="false">
		<appender-ref ref="STDOUT" />
	</logger>

	<logger name="org.eclipse.californium.core.network.interceptors.MessageTracer" level="DEBUG" additivity="false">
		<appender-ref ref="STDOUT" />
	</logger>

```

Results in:

```
INFO [ReliabilityLayer]: ReliabilityLayer uses ACK_TIMEOUT=200, ACK_RANDOM_FACTOR=1.0, and ACK_TIMEOUT_SCALE=1.0 as default (o.e.c.c.n.s.ReliabilityLayer.<init>:82)
INFO [ReliabilityLayer]: ReliabilityLayer uses ACK_TIMEOUT=200, ACK_RANDOM_FACTOR=1.0, and ACK_TIMEOUT_SCALE=1.0 as default (o.e.c.c.n.s.ReliabilityLayer.<init>:82)
DEBUG [ReliabilityLayer]: Exchange[L1] send request, failed transmissions: 0 (o.e.c.c.n.s.ReliabilityLayer.sendRequest:93)
DEBUG [ReliabilityLayer]: Exchange[L1] prepare retransmission for CON-GET    MID=   -1, Token=null, OptionSet={"Observe":0, "Uri-Path":"resX"}, no payload (o.e.c.c.n.s.ReliabilityLayer.sendRequest:99)
INFO [MessageTracer]: UDP(127.0.0.1:45101) ==> req CON-GET    MID=38855, Token=9F40B067D4E868F5, OptionSet={"Observe":0, "Uri-Path":"resX"}, no payload (o.e.c.c.n.i.MessageTracer.receiveRequest:58)
DEBUG [ReliabilityLayer]: Exchange[R2] send response CON-2.05   MID=   -1, Token=null, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes, failed transmissions: 0 (o.e.c.c.n.s.ReliabilityLayer.sendResponse:119)
DEBUG [ReliabilityLayer]: Exchange[R2] prepare retransmission for CON-2.05   MID=   -1, Token=null, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes (o.e.c.c.n.s.ReliabilityLayer.sendResponse:145)
INFO [MessageTracer]: UDP(127.0.0.1:45101) <== res CON-2.05   MID=32190, Token=9F40B067D4E868F5, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes (o.e.c.c.n.i.MessageTracer.sendResponse:48)
DEBUG [ReliabilityLayer]: Exchange[L1] acknowledging CON response (o.e.c.c.n.s.ReliabilityLayer.receiveResponse:320)
INFO [MessageTracer]: UDP(127.0.0.1:45101) ==> emp ACK        MID=32190 (o.e.c.c.n.i.MessageTracer.receiveEmptyMessage:68)
DEBUG [ReliabilityLayer]: Exchange[R2] acknowledge ACK        MID=32190 for response CON-2.05   MID=32190, Token=9F40B067D4E868F5, OptionSet={"Observe":0}, canceled ""resX says hi for the 1 ".. 29 bytes (1 msg observer) (o.e.c.c.n.s.ReliabilityLayer.receiveEmptyMessage:368)
DEBUG [ReliabilityLayer]: Exchange[R2] send response null-4.04   MID=   -1, Token=null, OptionSet={}, no payload, failed transmissions: 0 (o.e.c.c.n.s.ReliabilityLayer.sendResponse:119)
TRACE [ReliabilityLayer]: Exchange[R2] switched response message type from null to ACK (request was CON) (o.e.c.c.n.s.ReliabilityLayer.sendResponse:137)
INFO [MessageTracer]: UDP(127.0.0.1:45101) <== res ACK-4.04   MID=38855, Token=9F40B067D4E868F5, OptionSet={}, no payload (o.e.c.c.n.i.MessageTracer.sendResponse:48)
```

> TRACE [ReliabilityLayer]: Exchange[R2] switched response message type from null to ACK (request was CON) 

Indicates, what happens "on my machine".

**Comment by rogierc** [comment]
CoapResource cancels the relation and issues the error response:
```
	public void clearAndNotifyObserveRelations(ResponseCode code) {
			for (ObserveRelation relation : observeRelations) {
			relation.cancel();
			relation.getExchange().sendResponse(new Response(code));
		}
	}

```
but the ObserveLayer also cancels when an error response is sent and sets the CON type. But it does not when the relation has already been cancelled (=> established == false):
```
	@Override
	public void sendResponse(final Exchange exchange, final Response response) {

		final ObserveRelation relation = exchange.getRelation();
		if (relation != null && relation.isEstablished()) {

			if (exchange.getRequest().isAcknowledged() || exchange.getRequest().getType() == Type.NON) {
				// Transmit errors as CON
				if (!ResponseCode.isSuccess(response.getCode())) {
					LOGGER.debug("response has error code {} and must be sent as CON", response.getCode());
					response.setType(Type.CON);
					relation.cancel();
                          . . . 
```
Aren't responsibilities mixed a bit here. Should clearAndNotifyObserveRelations only issue an error message and leave cancelling to the observeLayer?

**Comment by boaks** [comment]
Maybe you can provide your logs, when executing the test in order to compare them?

`relation.isEstablished()` returns `false` after `cancel`.

**Comment by rogierc** [comment]
The test logging gives same result on my machine:
```
13:27:59.577 INFO [MessageTracer]: UDP(127.0.0.1:46022) <== res ACK-4.04   MID=55111, Token=531B5D42971F220D, OptionSet={}, no payload (o.e.c.c.n.i.MessageTracer.sendResponse:48)
```
The CON-4.04 response is seen in the application logging. When timing is a factor - that could explain.

**Comment by boaks** [comment]
> Aren't responsibilities mixed a bit here. 

Sure. 

The `CoapResource` synchronizes on nodes, and calls child and parent. Ideal for dead-locks. And there are for very sure much more in Californium, which may be improved. 

For the 3.0 I already improved a lot! And yes, there is also some stuff pending.
But I can't see, that someone else is working on the issues and so that pending stuff must be post postponed in order to benefit from the already corrected ones.

**Comment by boaks** [comment]
> The test logging gives same result on my machine:

Great, so i don't think this is a "real" difference in 2.6.5 and 3.0, at least no deterministic one.

Would it be possible, to check now, if the PRs are fixing the reported issue?

**Comment by rogierc** [comment]
Fix observe-server 2.6 #1758: all tests succeed in my environment. The bug did not manifest in my application - so cannot test there.

**Comment by boaks** [comment]
Thanks! So wait for @sbernard31 to retest with the PR.

**Comment by sbernard31** [comment]
> So wait for @sbernard31 to retest with the PR.

My current set-up to test this issue is based on recent modification of Leshan. So I have no easy way to integrate this PR and test it in Leshan for now. 

I guess I need to first move forward on : https://github.com/eclipse/leshan/pull/1073

**Comment by boaks** [comment]
cherry-pickung to 3.0.0-M3.x either PR #1758 or PR #1759 should be possible within a few minutes.

Anyway, I completed the unit tests in ObserveTest showed also some more defects. To fix them, requires more changes. We will see.

**Comment by sbernard31** [comment]
> cherry-pickung to 3.0.0-M3.x either PR #1758 or PR #1759 should be possible within a few minutes.

I will try this.

**Comment by sbernard31** [comment]
I cherry picked :
 - 45beaa792a1a02ca4f7c3c300a509d828f1494bc
 - d95206f6eb1afe8f1f24256542686c20b079e8b4
 - 3a6bb22a28ad6ea3e52f5420993cf108a0ffac35
 - a526d1275d9f30df14d75d780ab65da636ec2af1
 
 to `3.0.0-M3.x`  (021bee79cfa336049a2ce786f961fff283747d9d)
 
My first results :  I still faced same behavior.  
I tested by building it with maven and also running it in eclipse. (same result for both test)
 
(There was some conflicts to handle on cherry pick about `Configuration`, I hope I didn't do a mistake when resolving it)

**Comment by boaks** [comment]
> I still faced same behavior.

What does the unit test "ObserveTest" reports? 
If that's not that "same behavior", can you provide a unit test, with that "same behavior"?
If that's that "same behavior", then just push your changes as PR towards the 3.0.0-M3.x.

**Comment by sbernard31** [comment]
"same behavior" is  what I explain above : not 4.04 answer + ExchangeCompleteException

> What does the unit test "ObserveTest" reports?

I guess you mean : `testObserveClientDeleteResource`
It is green to me.  Here is some logs.
```
17:45:28.583 TRACE [ReliabilityLayer]: ReliabilityLayer uses ACK_TIMEOUT=200, ACK_RANDOM_FACTOR=1.0, and ACK_TIMEOUT_SCALE=1.0 as default (o.e.c.c.n.s.ReliabilityLayer.<init>:82)
17:45:28.639 TRACE [ReliabilityLayer]: ReliabilityLayer uses ACK_TIMEOUT=200, ACK_RANDOM_FACTOR=1.0, and ACK_TIMEOUT_SCALE=1.0 as default (o.e.c.c.n.s.ReliabilityLayer.<init>:82)
17:45:28.667 DEBUG [ReliabilityLayer]: Exchange[L1] send request (o.e.c.c.n.s.ReliabilityLayer.sendRequest:93)
17:45:28.667 DEBUG [ReliabilityLayer]: Exchange[L1] prepare retransmission for CON-GET    MID=   -1, Token=null, OptionSet={"Observe":0, "Uri-Path":"resX"}, no payload (o.e.c.c.n.s.ReliabilityLayer.prepareRequest:103)
17:45:28.682 INFO [MessageTracer]: UDP(127.0.0.1:46639) ==> req CON-GET    MID=27862, Token=3B67AA2B54E79D39, OptionSet={"Observe":0, "Uri-Path":"resX"}, no payload (o.e.c.c.n.i.MessageTracer.receiveRequest:58)
17:45:28.691 DEBUG [ReliabilityLayer]: Exchange[R2] send response CON-2.05   MID=   -1, Token=null, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes (o.e.c.c.n.s.ReliabilityLayer.sendResponse:128)
17:45:28.692 DEBUG [ReliabilityLayer]: Exchange[R2] prepare retransmission for CON-2.05   MID=   -1, Token=null, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes (o.e.c.c.n.s.ReliabilityLayer.prepareResponse:156)
17:45:28.692 INFO [MessageTracer]: UDP(127.0.0.1:46639) <== res CON-2.05   MID=26712, Token=3B67AA2B54E79D39, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes (o.e.c.c.n.i.MessageTracer.sendResponse:48)
17:45:28.699 DEBUG [ReliabilityLayer]: Exchange[L1] acknowledging CON response (o.e.c.c.n.s.ReliabilityLayer.processResponse:324)
17:45:28.700 INFO [MessageTracer]: UDP(127.0.0.1:46639) ==> emp ACK        MID=26712 (o.e.c.c.n.i.MessageTracer.receiveEmptyMessage:68)
17:45:28.701 DEBUG [ReliabilityLayer]: Exchange[R2] acknowledge ACK        MID=26712 for response CON-2.05   MID=26712, Token=3B67AA2B54E79D39, OptionSet={"Observe":0}, ""resX says hi for the 1 ".. 29 bytes (2 msg observer) (o.e.c.c.n.s.ReliabilityLayer.processEmptyMessage:378)
17:45:28.706 DEBUG [ReliabilityLayer]: Exchange[R2] send response CON-4.04   MID=   -1, Token=null, OptionSet={}, no payload (o.e.c.c.n.s.ReliabilityLayer.sendResponse:128)
17:45:28.707 DEBUG [ReliabilityLayer]: Exchange[R2] prepare retransmission for CON-4.04   MID=   -1, Token=null, OptionSet={}, no payload (o.e.c.c.n.s.ReliabilityLayer.prepareResponse:156)
17:45:28.707 INFO [MessageTracer]: UDP(127.0.0.1:46639) <== res CON-4.04   MID=26713, Token=3B67AA2B54E79D39, OptionSet={}, no payload (o.e.c.c.n.i.MessageTracer.sendResponse:48)
17:45:28.710 DEBUG [ReliabilityLayer]: Exchange[L3] acknowledging CON response (o.e.c.c.n.s.ReliabilityLayer.processResponse:324)
17:45:28.711 INFO [MessageTracer]: UDP(127.0.0.1:46639) ==> emp ACK        MID=26713 (o.e.c.c.n.i.MessageTracer.receiveEmptyMessage:68)
17:45:28.711 DEBUG [ReliabilityLayer]: Exchange[R2] acknowledge ACK        MID=26713 for response CON-4.04   MID=26713, Token=3B67AA2B54E79D39, OptionSet={}, no payload (2 msg observer) (o.e.c.c.n.s.ReliabilityLayer.processEmptyMessage:378)
```

>  If that's not that "same behavior", can you provide a unit test, with that "same behavior"?

I will try to do it.
I guess the main difference is that we didn't use `coapResource.delete();` because my Resource handle a hierarchy of resource and so there is not 1 resource Object by real coap ressource. (I'm not sure, I'm clear)
In Leshan, we have one `ObjectResource` which handle all LWM2M resources under this object.
(e.g. /3, /3/0, /3/0/1, /3/0/11/1 all those resources are handled by only 1 instance of `ObjectResource` which extends `CoapResource`)
If a LWM2M resource is deleted, we just call `CoapResource.changed()` with a custom `ObserveRelationFilter`.  This triggers GET request again which returns a 4.04 has the resource doesn't exist anymore.

**Comment by boaks** [comment]
:-).

I was expecting something as that. 
Years ago I introduced that ObserveRelationFilter and I already wondered, how leshan is trying to delete a instance or resource. 
I will add that to the unit test and see, if it works now. No need for you to try to reproduce it.

**Comment by boaks** [comment]
Try to cherry-pick 1347359 and check, if that solves it.
At least the "testObserveNonErrorResponse" should be now close to your usage.

**Comment by sbernard31** [comment]
I tested with 1347359  (I needed to adapt some more code about ResponseCode.isSuccess())
== > No more exception and the 4.04 is sent by the CoAP server. 

If I get it correctly, the CoAP client removes the `Observation` from the `ObservationStore` too ? 
I would say this is the right behavior. :thinking: 
Currently in Leshan there is no easy way to know this `Observation` was removed from the store but I guess this is probably a Leshan code issue (we need maybe to add some event on our store implementation).

**Comment by boaks** [comment]
> If I get it correctly, the CoAP client removes the Observation from the ObservationStore too ?
> I would say this is the right behavior. thinking

At least it was my intention, that error notifies are handled accordingly.

**Comment by boaks** [comment]
The fix for the master branch is merged.
I'm not sure, what will be a good solution for 2.6. 
The current PR addresses only the bug using "CoapResource.delete()". Apply/backport commit 1347359 to 2.6 may come with more risks, then currently visible. So, I would at least wait for some time, before trying that.

**Comment by sbernard31** [comment]
For people using the only stable version of Leshan : 1.x there is no way to migrate to 3.0.0.

**Comment by boaks** [comment]
AFAIK, that bug is only on the lwm2m-device side, right?

(And, for sure, any contribution to fix this on 2.6.x is welcome. Also after the 2.6.6. Ideas, what need to be fixed, could be gathered from the fix for 3.0.0.)

**Comment by boaks** [comment]
@sbernard31 

I don't think anyone will work on this, or? So would got to close it with "wontfix" for 2.6.x and 2.7.x

**Comment by sbernard31** [comment]
I'm not sure to get the question here ?

**Comment by boaks** [comment]
Yea "broken" English.

I would like to close this even in the state "wontfix" for the 2.6.x and 2.7.x. Users depending on the function a recommended to migrate to 3.2.0.

If you fell, that keeping it open is worth, I can also leave it open.

**Comment by boaks** [comment]
Thanks, so I close it.
