### ISSUE TITLE
Public key's ec-group must be supported!

### ISSUE THREAD

**Issue by davidsloan** [eclipse/californium#2002]
Hello

Thank you for all your work on this library!

I'm working on updating the [Stream Reactor Coap connector ](https://github.com/lensesio/stream-reactor) from Californium and Scandium 2.x to 3.5.

However we have a [test case](https://github.com/lensesio/stream-reactor/blob/master/kafka-connect-coap/src/test/scala/com/datamountaineer/streamreactor/connect/coap/connection/TestDTLSConnection.scala#L26) using PEM keys.  Looking into it they are using RSA keys (public key is X.509 and private is PKCS#8).

The test runs a Coap server and attempts to connect.

However whilst the test passes for 2.0 it does not appear to work for 3.4 (and 3.5 which I see you have just released).

On the client side, I have altered the code in the connector using the migration guide (roughly) from this:
```
        val psk = new InMemoryPskStore()
        psk.setKey(setting.identity, setting.secret.value().getBytes())
        psk.addKnownPeer(addr, setting.identity, setting.secret.value().getBytes())
        builder.setPskStore(psk)

        if (setting.privateKey.isDefined) {
          builder.setSupportedCipherSuites(Array[CipherSuite](CipherSuite.TLS_PSK_WITH_AES_128_CCM_8, CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA256))
          builder.setIdentity(setting.privateKey.get, setting.publicKey.get)
        }
       client.setEndpoint(new CoapEndpoint(new DTLSConnector(builder.build()), NetworkConfig.getStandard))
```
to this:

```
        val psk = new AdvancedMultiPskStore()
        psk.setKey(setting.identity, setting.secret.value().getBytes())
        psk.addKnownPeer(addr, setting.identity, setting.secret.value().getBytes())
        builder.setAdvancedPskStore(psk)

        if (setting.privateKey.isDefined) {
          builder.set(DtlsConfig.DTLS_CIPHER_SUITES, Lists.newArrayList(CipherSuite.TLS_PSK_WITH_AES_128_CCM_8, CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA256))
          builder.setCertificateIdentityProvider(
            new SingleCertificateProvider(
              setting.privateKey.get,
              setting.publicKey.get
            )
          )
        }
       client.setEndpoint(new CoapEndpoint.Builder()
         .setConnector(new DTLSConnector(builder.build()))
         .build())

```

However running the scenario this is the stack trace I receive:

```
Public key's ec-group must be supported!
java.lang.IllegalArgumentException: Public key's ec-group must be supported!
	at org.eclipse.californium.scandium.dtls.x509.SingleCertificateProvider.<init>(SingleCertificateProvider.java:146)
	at com.datamountaineer.streamreactor.connect.coap.connection.DTLSConnectionFn$.apply(DTLSConnectionFn.scala:95)
	at com.datamountaineer.streamreactor.connect.coap.connection.TestDTLSConnection.$anonfun$new$1(TestDTLSConnection.scala:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)
	at com.datamountaineer.streamreactor.connect.coap.connection.TestDTLSConnection.org$scalatest$BeforeAndAfter$$super$runTest(TestDTLSConnection.scala:17)
	at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:213)
	at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:203)
	at com.datamountaineer.streamreactor.connect.coap.connection.TestDTLSConnection.runTest(TestDTLSConnection.scala:17)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1296)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1295)
	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1879)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)
	at com.datamountaineer.streamreactor.connect.coap.connection.TestDTLSConnection.org$scalatest$BeforeAndAfter$$super$run(TestDTLSConnection.scala:17)
	at org.scalatest.BeforeAndAfter.run(BeforeAndAfter.scala:273)
	at org.scalatest.BeforeAndAfter.run$(BeforeAndAfter.scala:271)
	at com.datamountaineer.streamreactor.connect.coap.connection.TestDTLSConnection.run(TestDTLSConnection.scala:17)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

Just in case it's useful, the keys we are using can be found here:
https://github.com/lensesio/stream-reactor/tree/master/kafka-connect-coap/src/test/resources/keys - privatekey-pkcs8.pem and publickey.pem
I've inspected these and they appear to be valid.

I'd really appreciate any help figuring out what is going on here!  I've tried variants of the code, including adding extra/all the cipher suites but that hasn't helped.

**Comment by boaks** [comment]
I'm not sure, if I understand your question and approach:

You wrote, you want to use RSA public/private keys. 
Your snippet 

```
builder.setSupportedCipherSuites(Array[CipherSuite](CipherSuite.TLS_PSK_WITH_AES_128_CCM_8, CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA256))
``` 

configures PSK cipher suites only. If you want to use RSA, that will require one of

Recommended ones:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 

Not (longer) recommended CBC ones:
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

In your case, you use not a x509 certificate (that's missing), you use RawPublickey (RFC 7250). 
That requires usually to setup the RawPubliKey trusts with each public keys, otherwise, every peer may be able to do a successful handshake.

When you configure it proper, then you will still get that Exception:

```
		SupportedGroup group = SupportedGroup.fromPublicKey(publicKey);
		if (group == null) {
			throw new IllegalArgumentException("Public key's ec-group must be supported!");
		}
```

That currently doesn't consider to use RawPublicKey with RSA (it's a left over from the times before RSA was supported, it's more or less a stupid bug). 
Any reasons, why you want to use RSA with RawPublicKey?

(I will try to fix it, but it may take 1-3 days or so. You may, if you want, just delete / comment out the `throw new IllegalArgumentException("Public key's ec-group must be supported!");` and see what happens.)

**Comment by boaks** [comment]
Setup RawPublicKey trusts.

```
NewAdvancedCertificateVerifier verifier = StaticNewAdvancedCertificateVerifier.builder()
   .setTrustedRPKs(new RawPublicKeyIdentity(<other peer's public key>)).build();
builder.setAdvancedCertificateVerifier(verifier);
```

or (for tests only):

```
NewAdvancedCertificateVerifier verifier = StaticNewAdvancedCertificateVerifier.builder()
   .setTrustAllRPKs().build();
builder.setAdvancedCertificateVerifier(verifier);
```

(This is the default for version before 3.0, but that trusts just all Raw Public Key certificates.)

**Comment by davidsloan** [comment]
Hi, and thank you for the speedy reply.

> Any reasons, why you want to use RSA with RawPublicKey?

I'm not entirely sure and will check with the developer who originally implemented the functionality.  From my perspective, as we supported it on the older version of the connector, we don't want to break the functionality for users upgrading.  If there's a really good reason not to support or it doesn't make sense with Coap then I will feed it back.

I've tried your tweaks in your last message and am still running up against the same error as you suspected.  If you were able to fix the issue that would be really amazing.

**Comment by boaks** [comment]
I'm not sure, if the old configuration was even running in the intended way. Or maybe I even don't understand the old intention.
The issue is more, that during the development of Californium, we added more and more verification to the configuration. With that, it may now be the case, that the misconfiguration is detected and previous just ignored.

RSA, AFAIK, was never really working for the 2.x, so if you configure the connector to use PSK and RSA in 2.x, I would assume, that it just takes only the PSK stuff. That would explain, why only PSK cipher suites are provided.

And it shows the dangerous gap in the previous configuration, where someone may consider to use RSA (with it's strength) but actually gets PSK.

So:
Please first check, what is really intendend.
PSK comes with it's security (pre-shared keys). 
And RSA, ECDSA, EDDSA comes with their security (private/public key).

And, if you go for private/public key, you should be aware, that for RFC7252 ECDSA is mandatory. Therefore this is very common. RSA requires more data to be transferred, and EDDSA requires a recent java or BC.

So, if you know, what the intention really was, we can make the configuration accordingly.
(And fix RawPublicKey for RSA :-) ).

**Comment by boaks** [comment]
> I've tried your tweaks in your last message and am still running up against the same error as you suspected. If you were able to fix the issue that would be really amazing.

Including 

> delete / comment out the throw new IllegalArgumentException("Public key's ec-group must be supported!");

?

**Comment by davidsloan** [comment]
> > I've tried your tweaks in your last message and am still running up against the same error as you suspected. If you were able to fix the issue that would be really amazing.
> 
> Including
> 
> > delete / comment out the throw new IllegalArgumentException("Public key's ec-group must be supported!");
> 
> ?

Sorry, no - I didn't get around to building the source or trying that one yet!

**Comment by davidsloan** [comment]
Thanks for the information, I'll get back to you when I have some answers.

**Comment by boaks** [comment]
Maybe, just ahead of "ghost discussion" what was considered to be working, but actually never did.
It's also a good idea, to verify the assumptions by a wireshark capture. See [IP Capturing](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing).

I assume, that using the old implementation, the capture shows only PSK handshakes, and no RSA at all.

**Comment by davidsloan** [comment]
We have taken the decision to deprecate our connector as it requires a lot of investment of time to ensure it works fully with the correct standard.  In addition it doesn't actually seem to have much usage that we can track.

Therefore closing this ticket... but thank you once again for your help.

**Comment by boaks** [comment]
Your welcome.

**Comment by boaks** [comment]
Just to mention:

PR #2004 will support now RPK for RSA.

I guess, your company is not the only one, who gets disappointed about the usage and the return of invest of coap. There are for sure many reasons, among them an "over optimistic forecasts" and too many troubles (especially with other libraries ;-) ). And maybe, it's even not clear, for which use-case this is good at all.

FMPOV, unless you have use-cases, where you want to use LTE-M or NB-IoT modems without something as "Gateway-service", that question is a good one.
  
On the other side, there is not too much stuff, which can compete in performance, scalability or robustness. And the features of the new versions, e.g. graceful restart, are really nice. OK, micro-service, in spite of stating the opposite, in fact slows down that much, that the performance will be lost again.   

Anyway, without usage, it's not worth to migrate. Even if I would guess, the "time consuming issues" you mentioned, are more the issues of the past. And they cause pain today, because you want to use the old suspicious configuration. If you start over, with some ideas, what you really want, e.g. support PSK, RPK, or X509 or all together, you will see, that using the new configuration API is much more simple and straight-forward, than the old one was.
