### ISSUE TITLE
Issue while doing retransmission

### ISSUE THREAD

**Issue by Rajsmit** [eclipse/californium#220]
Hi,

using master branch
We have observed some exception while re-transmission is happening. Please find the log and let us know why this is happening and how to fix it.

02-23 13:42:19.630 2042-2092/com.ikea.tradfri.lighting E/ReliabilityLayer: Exception in MessageObserver: Attempt to read from field 'int org.eclipse.californium.core.coap.CoAP$Code.value' on a null object reference
                                                                           java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.californium.core.coap.CoAP$Code.value' on a null object reference
                                                                               at org.eclipse.californium.core.network.serialization.DataSerializer.serializeRequest(DataSerializer.java:51)
                                                                               at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:567)
                                                                               at org.eclipse.californium.core.network.stack.CoapUdpStack$StackBottomAdapter.sendRequest(CoapUdpStack.java:208)
                                                                               at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:65)
                                                                               at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:115)
                                                                               at org.eclipse.californium.core.network.stack.ReliabilityLayer$2.retransmit(ReliabilityLayer.java:111)
                                                                               at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.run(ReliabilityLayer.java:366)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by Rajsmit** [comment]
Hi,

Could you please let us know any update on this issue?

Thanks,
Rajesh Kumar.

**Comment by sophokles73** [comment]
Hi @Rajsmit,

this is an open source project and we are trying our best to build great software and help people with problems using the software. I appreciate the fact that you are using Californium and consider it worth spending your time on. However, this does not entitle you to state any demands and/or pressure people to solve your problems. In fact, open source software is based on the community's shared effort to improve the software. So, I would really appreciate it, if you would you could find a less demanding tone.

Apart from that, I will try to find some time and take a look. Maybe you can do the same and provide a patch if you are successful ...

**Comment by sophokles73** [comment]
First of all, can you indicate which commit you are using? Has this problem been popping up just recently?

**Comment by boaks** [comment]
Additionaly, if you enable logging, could you post the log of the first sending this message (though this seems to be the retransmission)?

**Comment by boaks** [comment]
Comparing the exception lines with the current master, it seems that your using a past commit.
Could you please retest the bug with the current master?

**Comment by Rajsmit** [comment]
Hi @sophokles73,

I understand your views and agree with you.

Hi @boaks,
We are using the code of master at commit ( 00efd32  on Oct 20, 2016).

This exception is not very frequent as only happens if re-transmission is required. 

We will share the more details with logging enabled once we will reproduced it.

Thanks,
Rajesh Kumar

**Comment by boaks** [comment]
@Rajsmit 

OK, so I would propose, that you try the current master.  
I think, I remember there was a fix for the code := null issue.
(Forcing a retransmission in general is easy,  just kill the coap server. The complex part may be, when to kill it :-) ).

**Comment by Rajsmit** [comment]
Thanks For the info. We have taken the latest master branch and Testing the fix.

**Comment by Rajsmit** [comment]
We have verified this issue has been fixed in latest master

**Comment by boaks** [comment]
Thanks for your verification and feedback!
