### ISSUE TITLE
CoAP over TCP response:: Getting closed connection error. 

### ISSUE THREAD

**Issue by ZankrutAntani** [eclipse/californium#330]
Hello Sir, 
While using Californium's latest build for CoAP over TCP - we're receiving an error while we hit from client. We can see the response coming up in Wireshark, however somehow it is not coming up in console. We have modified CoAPEndpoint.java for creating TCP Server Connector. 
We're trying with Hello World Programme. 
Here's the error: 
SEVERE: Exception in channel handler chain for endpoint /127.0.0.1:5683. Closing connection.
java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to org.eclipse.californium.elements.RawData
	at org.eclipse.californium.elements.tcp.DispatchHandler.channelRead(DispatchHandler.java:35)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Unknown Source)

any pointers would be of great help. 

Thanks! 

Best,
Zankrut.

**Comment by boaks** [comment]
> Californium's latest build for CoAP over TCP

Can you provide the commit or branch you used?

**Comment by ZankrutAntani** [comment]
Thanks much for your quick response. I have used below branch. I've used Californium - core.

https://github.com/eclipse/californium

**Comment by boaks** [comment]
See PR #331
It's based on branch 2.0.x.
As far as I could test it, it works without that exception.

**Comment by boaks** [comment]
I pushed the changes to branch "hw_server_tcp" on the "https://github.com/eclipse/californium" repository.
So, please "fetch" from the repository and "checkout" that branch and repeat your tests.

**Comment by ZankrutAntani** [comment]
Thanks a lot for your quick assistance! It has started working now!!

**Comment by boaks** [comment]
If it works for you, can you close the issue?

**Comment by ZankrutAntani** [comment]
Sure Sir. Thanks much for your help.
