### ISSUE TITLE
Scandium/ DTLS (Timeout?) Issues

### ISSUE THREAD

**Issue by peterkappelt** [eclipse/californium#366]
Hi everyone,

I'm currently developing with Californium & Scandium. The software shall react to certain commands over TCP sockets and translate them into certain CoAP requests.
The software is working just fine on my setups, but a beta tester has issues while running my software.
Since I can't reproduce this problem on my systems it is quite hard to debug for me.

The initialization of the library looks like follows:

<details>
  <summary>Click to expand</summary>

```Java


try{
  // load key store
  KeyStore keyStore = KeyStore.getInstance("JKS");
  InputStream in = getClass().getClassLoader().getResourceAsStream(KEY_STORE_LOCATION);
  keyStore.load(in, KEY_STORE_PASSWORD.toCharArray());
  in.close();

  // load trust store
  KeyStore trustStore = KeyStore.getInstance("JKS");
  in = getClass().getClassLoader().getResourceAsStream(TRUST_STORE_LOCATION);
  trustStore.load(in, TRUST_STORE_PASSWORD.toCharArray());
  in.close();

  // You can load multiple certificates if needed
  Certificate[] trustedCertificates = new Certificate[1];
  trustedCertificates[0] = trustStore.getCertificate("root");

  DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
  builder.setAddress(new InetSocketAddress(0));
  builder.setPskStore(new StaticPskStore("Client_identity", psk.getBytes()));
  builder.setIdentity((PrivateKey)keyStore.getKey("client", KEY_STORE_PASSWORD.toCharArray()), keyStore.getCertificateChain("client"), true);
  builder.setTrustStore(trustedCertificates);
	
  //try to fix timeouts at user
  builder.setRetransmissionTimeout(50000);
	
  dtlsConnector = new DTLSConnector(builder.build());

} catch (Exception e) {
  System.err.println("[Coap] Error in Coap.setPSK (while initializing keystore): ");
  e.printStackTrace();
  System.exit(-1);
}

//try to fix timeouts at user
client.setEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard().set(Keys.ACK_TIMEOUT, 40000)));
client.setTimeout(60000);

//client.setEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));

```
</details>

The full code can be seen here: https://github.com/peterkappelt/kCoAPSocket

The user triggers an action and the well-known of a device is fetched. He gets the following output:
<details>
<summary>Click to expand</summary>

```
kCoAPSocket 0.0.5-snapshot

[TcpServerThread] Binding of socket @ port 1505 successfull.
Jul 26, 2017 6:07:06 PM org.eclipse.californium.core.network.config.NetworkConfig load
INFORMATION: loading properties from file /root/tradfri-java/Tradfri-FHEM/kCoAPSocket/kCoAPSocket/Californium.properties
Jul 26, 2017 6:07:10 PM org.eclipse.californium.core.network.CoapEndpoint start
INFORMATION: Starting endpoint at 0.0.0.0/0.0.0.0:0
Jul 26, 2017 6:07:11 PM org.eclipse.californium.scandium.DTLSConnector start
INFORMATION: DTLS connector listening on [0.0.0.0/0.0.0.0:59593] with MTU [1.280] using (inbound) datagram buffer size [16.474 bytes]
Jul 26, 2017 6:07:11 PM org.eclipse.californium.core.CoapClient setEndpoint
INFORMATION: Started set client endpoint 0.0.0.0/0.0.0.0:59593
2017-07-26 18:07:20:  10 FINE [SweepDeduplicator$SweepAlgorithm]: Sweep run took 5ms - (org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.java:180) sweep() in thread Deduplicator1
[TcpServerThread] Connection at port 1505 opened
[TcpServerThread] Fetching well-known...
11 FINE [Connection]: Handshake with [/192.168.0.138:5684] has been started - (org.eclipse.californium.scandium.dtls.Connection.java:865) handshakeStarted() in thread DTLS-Sender-0.0.0.0/0.0.0.0:59593 at (2017-07-26 18:07:26)
11 FINE [ECDHECryptography$SupportedGroup]: Group [brainpoolP256r1] is not supported by JRE - (org.eclipse.californium.scandium.dtls.cipher.ECDHECryptography$SupportedGroup.java:380) <init>() in thread DTLS-Sender-0.0.0.0/0.0.0.0:59593 at (2017-07-26 18:07:27)
11 FINE [ECDHECryptography$SupportedGroup]: Group [brainpoolP384r1] is not supported by JRE - (org.eclipse.californium.scandium.dtls.cipher.ECDHECryptography$SupportedGroup.java:388) <init>() in thread DTLS-Sender-0.0.0.0/0.0.0.0:59593 at (2017-07-26 18:07:27)
11 FINE [ECDHECryptography$SupportedGroup]: Group [brainpoolP512r1] is not supported by JRE - (org.eclipse.californium.scandium.dtls.cipher.ECDHECryptography$SupportedGroup.java:396) <init>() in thread DTLS-Sender-0.0.0.0/0.0.0.0:59593 at (2017-07-26 18:07:27)
16 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-1 at (2017-07-26 18:07:27)
16 FINE [ClientHandshaker]: Processing Handshake (22) message from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:195) doProcessMessage() in thread pool-1-thread-1 at (2017-07-26 18:07:27)
16 FINE [ClientHandshaker]: Processed HELLO_VERIFY_REQUEST (3) message with sequence no [0] from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:406) doProcessMessage() in thread pool-1-thread-1 at (2017-07-26 18:07:27)
17 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-2 at (2017-07-26 18:07:27)
17 FINE [ClientHandshaker]: Processing Handshake (22) message from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:195) doProcessMessage() in thread pool-1-thread-2 at (2017-07-26 18:07:27)
17 FINE [ClientHandshaker]: Processed SERVER_HELLO (2) message with sequence no [1] from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:406) doProcessMessage() in thread pool-1-thread-2 at (2017-07-26 18:07:27)
18 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-3 at (2017-07-26 18:07:27)
18 FINE [ClientHandshaker]: Processing Handshake (22) message from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:195) doProcessMessage() in thread pool-1-thread-3 at (2017-07-26 18:07:27)
2017-07-26 18:07:30:  10 FINE [SweepDeduplicator$SweepAlgorithm]: Sweep run took 0ms - (org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.java:180) sweep() in thread Deduplicator1
18 FINE [ClientHandshaker]: Processed SERVER_HELLO_DONE (14) message with sequence no [2] from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:406) doProcessMessage() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
19 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-4 at (2017-07-26 18:07:32)
20 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-5 at (2017-07-26 18:07:32)
21 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-6 at (2017-07-26 18:07:32)
16 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-1 at (2017-07-26 18:07:32)
17 FINE [ClientHandshaker]: Processing Change Cipher Spec (20) message from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:195) doProcessMessage() in thread pool-1-thread-2 at (2017-07-26 18:07:32)
17 FINE [ClientHandshaker]: Processed Change Cipher Spec (20) message from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:406) doProcessMessage() in thread pool-1-thread-2 at (2017-07-26 18:07:32)
18 FINE [DTLSConnector]: Received Handshake (22) record from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.DTLSConnector.java:537) processHandshakeRecord() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
18 FINE [ClientHandshaker]: Processing Handshake (22) message from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:195) doProcessMessage() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
18 FINE [DTLSConnector$5]: Session with [/192.168.0.138:5684] established, now sending deferred message - (org.eclipse.californium.scandium.DTLSConnector$5.java:871) sessionEstablished() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
18 FINE [Connection]: Session with [/192.168.0.138:5684] has been established - (org.eclipse.californium.scandium.dtls.Connection.java:871) sessionEstablished() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
18 FINE [Connection]: Handshake with [/192.168.0.138:5684] has been completed - (org.eclipse.californium.scandium.dtls.Connection.java:877) handshakeCompleted() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
18 FINE [ClientHandshaker]: Processed FINISHED (20) message with sequence no [3] from peer [/192.168.0.138:5684] - (org.eclipse.californium.scandium.dtls.ClientHandshaker.java:406) doProcessMessage() in thread pool-1-thread-3 at (2017-07-26 18:07:32)
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6761, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6761, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6762, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6762, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6763, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6763, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6764, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6764, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6765, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6765, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6766, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6766, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6767, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6767, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6768, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6768, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for MID KeyMID[6769, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:275) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [UdpMatcher]: Closed open request [KeyMID[6769, c0a8008a:5684]] - (org.eclipse.californium.core.network.UdpMatcher.java:330) receiveResponse() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [BlockwiseLayer]: requested resource body exceeds max buffer size [2.048], aborting request - (org.eclipse.californium.core.network.stack.BlockwiseLayer.java:535) handleBlock2Response() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [ExchangeCleanupLayer$CancelledMessageObserver]: completing canceled request [MID=6.761, token=9e77181f8f435a15] - (org.eclipse.californium.core.network.stack.ExchangeCleanupLayer$CancelledMessageObserver.java:43) onCancel() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
2017-07-26 18:07:32:  13 FINE [InMemoryMessageExchangeStore]: removing exchange for token KeyToken[9e77181f8f435a15, c0a8008a:5684] - (org.eclipse.californium.core.network.InMemoryMessageExchangeStore.java:260) remove() in thread CoapEndpoint-0.0.0.0/0.0.0.0:0#1
[TcpServerThread] Error in client socket, ending this socket: null
java.lang.NullPointerException
	at net.kappelt.kCoAPSocket.TcpServerHandler.run(TcpServerHandler.java:53)
	at java.lang.Thread.run(Thread.java:745)
2017-07-26 18:07:41:  10 FINE [SweepDeduplicator$SweepAlgorithm]: Sweep run took 0ms - (org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.java:180) sweep() in thread Deduplicator1
2017-07-26 18:07:51:  10 FINE [SweepDeduplicator$SweepAlgorithm]: Sweep run took 0ms - (org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.java:180) sweep() in thread Deduplicator1
```

</details>

The part that fails is here:
<details>
<summary>Click to expand</summary>

```Java


try{
  // read data and write data
  BufferedReader inData = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
  String dataLine = null;

  PrintWriter outData = new PrintWriter(clientSocket.getOutputStream(), true);

  //this is used to stop the thread, once the connection is broken
  Boolean executeLoop = true;

  System.out.println("[TcpServerThread] Fetching well-known...");
  System.out.println("Well Known: " + coapClient.get("coaps://" + gatewayAddress + "/.well-known/core").getResponseText());

  while(executeLoop){
  ...
  }
}catch(Exception e){
  System.err.println("[TcpServerThread] Error in client socket, ending this socket: " + e.getMessage());
  e.printStackTrace();
}

```

</details>

I'd propably do some more lowlevel debugging, though its quite hard to do so because I'm unable to access the system with the problem. Is there anything obvious in the log? What else should I ask the user to investigate?
If I'd have to make an educated guess: Maybe this is related to #235 

Thanks in advance,
Peter Kappelt

**Comment by sophokles73** [comment]
it seems that the body of the `/.well-known/core` resource exceeds 2048 bytes and can therefore not be downloaded by the blockwise layer. You can either increase the maximum allowed body size, e.g. using something like `NetworkConfig.setInt(NetworkConfig.MAX_RESOURCE_BODY_SIZE, 4096)` to set it to 4kb, or you need to make sure that the body of the `/.well-known/core` resource is always smaller than 2kb.

**Comment by peterkappelt** [comment]
Thank You! That was the problem.
I actually saw this part with the block size warning, but the messages above ("Closed open request" an "removing key exchange") confused me and I thought that I would need to fix them first.
