### ISSUE TITLE
IllegalArgumentException when logging URI

### ISSUE THREAD

**Issue by swachter** [eclipse/californium#481]
Tested with Version 2.0.0-M5

    Exception in thread "main" java.lang.IllegalArgumentException: Malformed escape pair at index 22: coap://0:0:0:0:0:0:0:1%lo:5683
	at java.net.URI.create(URI.java:852)
	at org.eclipse.californium.elements.UDPConnector.getUri(UDPConnector.java:403)
	at org.eclipse.californium.core.network.CoapEndpoint.getUri(CoapEndpoint.java:585)
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:414)
	at org.eclipse.californium.core.CoapServer.start(CoapServer.java:215)

The scapegoat is CoapEndpoint:414

    			LOGGER.log(Level.INFO, "Starting endpoint at {0}", getUri());

where the URI is logged. In master `getAddress()` was logged.

**Comment by sophokles73** [comment]
The *getUri* method has been removed/replaced on 2.0.x since M5, so this shouldn't be a problem anymore. Can you confirm that you do not run into this when using a 2.0.x nightly?

**Comment by swachter** [comment]
It works with 2.0.X.
