### ISSUE TITLE
Cipher init in every message decryption

### ISSUE THREAD

**Issue by joechen2010** [eclipse/californium#609]
DTLS performance penalty is the decrypt the message in CCMBlockCipher. the cipher init every message and it 's a synchronized action, should be move to DTLSession when it creating.
`Cipher cipher = Cipher.getInstance(CIPHER_NAME); `
`cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(key, KEY_TYPE));`
found branch: 2.0.0-M9 

thread dump :

"DTLS-Connection-Handler-47" #171 daemon prio=5 os_prio=0 tid=0x0000000000868000 nid=0x66e86 runnable [0x00007f1d8b7f6000]
   java.lang.Thread.State: RUNNABLE
                at java.util.Arrays.copyOfRange(Arrays.java:3664)
                at java.lang.String.<init>(String.java:207)
                at java.lang.String.toUpperCase(String.java:2810)
                at java.security.Provider$ServiceKey.<init>(Provider.java:872)
                at java.security.Provider$ServiceKey.<init>(Provider.java:865)
                at java.security.Provider.getService(Provider.java:1039)
                - locked <0x00000003c0b1b8f8> (a com.sun.crypto.provider.SunJCE)
                at sun.security.jca.ProviderList$ServiceList.tryGet(ProviderList.java:444)
                at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList.java:376)
                at sun.security.jca.ProviderList$ServiceList$1.hasNext(ProviderList.java:486)
                at javax.crypto.Cipher.getInstance(Cipher.java:513)
                at org.eclipse.californium.scandium.dtls.cipher.CCMBlockCipher.decrypt(CCMBlockCipher.java:310)
                at org.eclipse.californium.scandium.dtls.Record.decryptAEAD(Record.java:619)
                at org.eclipse.californium.scandium.dtls.Record.decryptFragment(Record.java:369)
                at org.eclipse.californium.scandium.dtls.Record.decryptApplicationMessage(Record.java:880)
                at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:848)
                at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:817)
                at org.eclipse.californium.scandium.DTLSConnector.processApplicationDataRecord(DTLSConnector.java:700)
                - locked <0x000000053cb4b450> (a org.eclipse.californium.scandium.dtls.DTLSSession)
                at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:561)
                at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:151)
                at org.eclipse.californium.scandium.DTLSConnector$2.run(DTLSConnector.java:536)
                at eu.javaspecialists.tjsn.concurrency.stripedexecutor.StripedExecutorService$SerialExecutor$1.run(StripedExecutorService.java:460)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)

"DTLS-Connection-Handler-42" #166 daemon prio=5 os_prio=0 tid=0x00007f1e60003000 nid=0x66e81 waiting for monitor entry [0x00007f1d8bcfb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
                at java.security.Provider.getService(Provider.java:1035)
                - waiting to lock <0x00000003c0b1b8f8> (a com.sun.crypto.provider.SunJCE)
                at sun.security.jca.ProviderList$ServiceList.tryGet(ProviderList.java:444)
                at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList.java:376)
                at sun.security.jca.ProviderList$ServiceList$1.hasNext(ProviderList.java:486)
                at javax.crypto.Cipher.getInstance(Cipher.java:513)
                at org.eclipse.californium.scandium.dtls.cipher.CCMBlockCipher.decrypt(CCMBlockCipher.java:310)
                at org.eclipse.californium.scandium.dtls.Record.decryptAEAD(Record.java:619)
                at org.eclipse.californium.scandium.dtls.Record.decryptFragment(Record.java:369)
                at org.eclipse.californium.scandium.dtls.Record.decryptApplicationMessage(Record.java:880)
                at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:848)
                at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:817)
                at org.eclipse.californium.scandium.DTLSConnector.processApplicationDataRecord(DTLSConnector.java:700)
                - locked <0x00000003c3804af0> (a org.eclipse.californium.scandium.dtls.DTLSSession)
                at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:561)
                at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:151)
                at org.eclipse.californium.scandium.DTLSConnector$2.run(DTLSConnector.java:536)
                at eu.javaspecialists.tjsn.concurrency.stripedexecutor.StripedExecutorService$SerialExecutor$1.run(StripedExecutorService.java:460)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)

"DTLS-Connection-Handler-35" #154 daemon prio=5 os_prio=0 tid=0x00007f1e48004800 nid=0x66e75 waiting for monitor entry [0x00007f1d909c8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
                at java.security.Provider.getService(Provider.java:1035)
                - waiting to lock <0x00000003c0b1b8f8> (a com.sun.crypto.provider.SunJCE)
                at sun.security.jca.ProviderList$ServiceList.tryGet(ProviderList.java:444)
                at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList.java:376)
                at sun.security.jca.ProviderList$ServiceList$1.hasNext(ProviderList.java:486)
                at javax.crypto.Cipher.getInstance(Cipher.java:513)
                at org.eclipse.californium.scandium.dtls.cipher.CCMBlockCipher.decrypt(CCMBlockCipher.java:310)
                at org.eclipse.californium.scandium.dtls.Record.decryptAEAD(Record.java:619)
                at org.eclipse.californium.scandium.dtls.Record.decryptFragment(Record.java:369)
                at org.eclipse.californium.scandium.dtls.Record.decryptApplicationMessage(Record.java:880)
                at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:848)
                at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:817)
                at org.eclipse.californium.scandium.DTLSConnector.processApplicationDataRecord(DTLSConnector.java:700)
                - locked <0x0000000444dcb330> (a org.eclipse.californium.scandium.dtls.DTLSSession)
                at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:561)
                at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:151)
                at org.eclipse.californium.scandium.DTLSConnector$2.run(DTLSConnector.java:536)
                at eu.javaspecialists.tjsn.concurrency.stripedexecutor.StripedExecutorService$SerialExecutor$1.run(StripedExecutorService.java:460)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)

**Comment by boaks** [comment]
Did you profile it? And does the profiling show, that the cpu spend in `getInstance` and `init` is the bottleneck?

**Comment by boaks** [comment]
I did some initial test with one client and static reused ciphers.
I get 20% more messages (1800 to 2200). So seems worth to invest some time.

**Comment by sbernard31** [comment]
I suspect this was a problem when I proposed this "little" enhancement : https://github.com/eclipse/californium/pull/385

It sounds to be well known issue : 
https://bugs.java.com/view_bug.do?bug_id=7092821
https://bugs.java.com/view_bug.do?bug_id=8172827

A common solution seems to cache Cipher (or any other object we instantiate like this) in threadlocal and call `.init()` before to use it.

**Comment by boaks** [comment]
I prepared a first PR. Nicce improvement about 20% (depending on the message size).
If someone can check the CBC cipher for that, this would be great.
If other bottleneck detected, don't hesitate to report them :-).

**Comment by boaks** [comment]
All results together:

windows 10
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

org.eclipse.californium.extplugtests.BenchmarkClient
-d64 -XX:+UseG1GC -Xmx2g
coaps://localhost:5784/benchmark?rlen=40 1000 5000

org.eclipse.californium.extplugtests.ExtendedTestServer
-d64 -XX:+UseG1GC -Xmx2g 
-onlyLoopback -noPlugtest

// init once
5000000 requests in 385612ms, 12966 reqs/s
5000000 requests in 381313ms, 13112 reqs/s
5000000 requests in 387289ms, 12910 reqs/s

// init on message
5000000 requests in 392561ms, 12736 reqs/s
5000000 requests in 388110ms, 12882 reqs/s
5000000 requests in 384122ms, 13016 reqs/s

// threadlocal (also init on message)
5000000 requests in 407513ms, 12269 reqs/s
5000000 requests in 407701ms, 12263 reqs/s
5000000 requests in 406746ms, 12292 reqs/s

At least for the 1.0.x and master, I think the theadlocal #614 with to changes only in CCMBlockCipher, will do a good job. For 2.0.x I'm not sure, if we should take the 5% benefit of #612 and invest some heap instead. Any opinion or other results and improvements?
