### ISSUE TITLE
DTLS requests with CON fail after longer network outage

### ISSUE THREAD

**Issue by henning77** [eclipse/californium#68]
My client sends regular messages (2 per second, each 256 bytes) via a mobile connection to a server, using CON, using the DTLSConnector of Californium 1.0.3.

After a longer network outage (no mobile connection at all for > 60s), the client fails to send any message to the server after the connection is restored. Every message sent fails with onError() of CoapHandler. Note that the client still tries to send during the network outage, regardless of the error.

The problem does not occur if I use the UDPConnector instead of DTLSConnector, or if I use NONs instead of CONs. In these cases, the client can successfully send messages again after the connection is restored.

**Comment by sophokles73** [comment]
This is most likely related to either
- a changing IP address at the client side, i.e. after your client has a mobile connection again, it is assigned a new IP address from the mobile network operator, and/or
- the mobile operator's firewall removing the port forwarding for UDP packets sent from the server to your client

When you use plain UDPConnector then every request "punches" a new hole in the firewall and the server can successfully receive the request and send an ACK (or response) to your client.

When you use DTLSConnector then with the first request being sent the client and server perform a handshake for establishing a DTLS session that is bound to the client's IP address and port.
When the client's IP address changes between subsequent requests the server may not be able to find the DTLS session using the client's IP:port as the index. In this case the existing DTLS session can be "resumed" by the client instead. For this to happen the DTLSConnector provides the `DTLSConnector.forceResumeSessionFor()` method. When you call this method, the connector will try to resume the existing session with the remote peer (the server in your case) the next time you send a message to it, thereby "informing" the peer about the client's new IP address:port.

**Comment by henning77** [comment]
Thank you! That seems to be the case. I have packet captures both on client and server. On the server side, I see the source port changing after the network outage (source IP stays the same).

If I understand correctly, the client should call `DTLSConnector.forceResumeSessionFor()` as soon as it sees a `CoapHandler.onError()`. I will try that and report back.

Would it be possible for the server side to automatically find the session if only the source port changes?

**Comment by sophokles73** [comment]
No, because the client is always identified by the combination of IP address and port. You could very well also have two clients run behind the same NAT router (i.e. using the same public IP address) but using different ports. The server would have no way of telling them apart. When a session is resumed, the client therefore sends the DTLS session ID to the server in order to allow him to find the corresponding session...

**Comment by henning77** [comment]
I implemented the approach, calling `DTLSConnector.forceResumeSessionFor()` on every onError().
Now I see a couple of errors both on client and server side, as soon as the network is re-established. It seems the session resumption is not successful:

**Server side log**
```
INFO  [2016-07-08 15:46:21,918] <DTLS-Receiver-0.0.0.0/0.0.0.0:38090> o.e.c.s.DTLSConnector: Unexpected error occurred while processing record from peer [/80.187.102.107:9875]
java.lang.NullPointerException: null
	at org.eclipse.californium.scandium.dtls.Record.decryptAEAD(Record.java:591)
	at org.eclipse.californium.scandium.dtls.Record.decryptFragment(Record.java:368)
	at org.eclipse.californium.scandium.dtls.Record.decryptHandshakeMessage(Record.java:876)
	at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:830)
	at org.eclipse.californium.scandium.dtls.Record.getFragment(Record.java:791)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecordWithConnection(DTLSConnector.java:753)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:690)
	at org.eclipse.californium.scandium.DTLSConnector.receiveNextDatagramFromNetwork(DTLSConnector.java:425)
	at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:101)
	at org.eclipse.californium.scandium.DTLSConnector$2.doWork(DTLSConnector.java:327)
	at org.eclipse.californium.scandium.DTLSConnector$Worker.run(DTLSConnector.java:1436)

INFO  [2016-07-08 15:46:31,215] <DTLS-Receiver-0.0.0.0/0.0.0.0:38090> o.e.c.s.DTLSConnector: Aborting handshake with peer [/80.187.102.107:9875]: The client's CertificateVerify message could not be verified.
```

**Client side**
```
java.lang.ClassCastException: org.eclipse.californium.scandium.dtls.FragmentedHandshakeMessage cannot be cast to org.eclipse.californium.scandium.dtls.HelloRequest
	at org.eclipse.californium.scandium.DTLSConnector.processDecryptedHandshakeMessage(DTLSConnector.java:767)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecordWithConnection(DTLSConnector.java:754)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:690)
	at org.eclipse.californium.scandium.DTLSConnector.receiveNextDatagramFromNetwork(DTLSConnector.java:425)
	at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:101)
	at org.eclipse.californium.scandium.DTLSConnector$2.doWork(DTLSConnector.java:327)
	at org.eclipse.californium.scandium.DTLSConnector$Worker.run(DTLSConnector.java:1436)
INFO  [2016-07-08 15:46:11,994] <DTLS-Receiver-0.0.0.0/0.0.0.0:41886> o.e.c.s.DTLSConnector: Aborting handshake with peer [/139.59.140.1:38091]: Unsupported key exchange algorithm

... a lot more Unsupported key exchange algorithm, one for each message sent...

ERROR [2016-07-08 15:46:19,018] <DTLS-Receiver-0.0.0.0/0.0.0.0:41886> o.e.c.s.d.ECDHServerKeyExchange: Could not verify the server's signature.
java.security.InvalidKeyException: No installed provider supports this key: (null)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1135)
	at java.security.Signature$Delegate.engineInitVerify(Signature.java:1167)
	at java.security.Signature.initVerify(Signature.java:457)
	at org.eclipse.californium.scandium.dtls.ECDHServerKeyExchange.verifySignature(ECDHServerKeyExchange.java:325)
	at org.eclipse.californium.scandium.dtls.ClientHandshaker.receivedServerKeyExchange(ClientHandshaker.java:426)
	at org.eclipse.californium.scandium.dtls.ClientHandshaker.doProcessMessage(ClientHandshaker.java:226)
	at org.eclipse.californium.scandium.dtls.Handshaker.processMessage(Handshaker.java:373)
	at org.eclipse.californium.scandium.DTLSConnector.processOngoingHandshakeMessage(DTLSConnector.java:783)
	at org.eclipse.californium.scandium.DTLSConnector.processDecryptedHandshakeMessage(DTLSConnector.java:770)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecordWithConnection(DTLSConnector.java:754)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:690)
	at org.eclipse.californium.scandium.DTLSConnector.receiveNextDatagramFromNetwork(DTLSConnector.java:425)
	at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:101)
	at org.eclipse.californium.scandium.DTLSConnector$2.doWork(DTLSConnector.java:327)
	at org.eclipse.californium.scandium.DTLSConnector$Worker.run(DTLSConnector.java:1436)
```

**Comment by sophokles73** [comment]
It's hard to tell what's happening based on the limited log. Can you increase the log level to FINEST?

Also, you are invoking `DTLSConnector.forceResumeSessionFor()` on the client only, don't you?

After you have invoked the method above, are you sending a single or multiple requests at once?

**Comment by henning77** [comment]
I will try again with increased logging.
Yes, only the client invokes `DTLSConnector.forceResumeSessionFor()`.
The client sends a request every 500ms, sequentially. On every call of `onError()`, it will call the method `DTLSConnector.forceResumeSessionFor()`.
Also the client never stops to send. So, if the network is down for a longer time period, many requests will be started and `onError()` / `DTLSConnector.forceResumeSessionFor()` will be triggered many times.

**Comment by sophokles73** [comment]
@henning77 

is this still an issue for you?

**Comment by henning77** [comment]
Sorry, I haven't gotten around to re-testing it with increased logging. I assume the issue is still there, however currently I don't have the infrastructure to re-test. If nobody else is experiencing a similiar issue with `forceResumeSessionFor()`, it's probably best to close the issue for now.

**Comment by sophokles73** [comment]
closed for now, feel free to re-open or create a new issue if you still run into this problem
