### ISSUE TITLE
start coapserver some error happen

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#680]
i start coapserver, stop coapserver, when i start coapserver again some error happen...

## when i start coapserver secend time, then error like this : 
java.lang.IllegalThreadStateException
        at java.lang.ThreadGroup.addUnstarted(ThreadGroup.java:867)[:1.8.0_161]
        at java.lang.Thread.init(Thread.java:405)[:1.8.0_161]
        at java.lang.Thread.init(Thread.java:349)[:1.8.0_161]
        at java.lang.Thread.<init>(Thread.java:678)[:1.8.0_161]
        at org.eclipse.californium.core.Utils$NamedThreadFactory.newThread(Utils.java:225)
        at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619)[:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932)[:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603)[:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)[:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)[:1.8.0_161]
        at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:154)
        at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.access$100(SweepDeduplicator.java:104)
        at org.eclipse.californium.core.network.deduplication.SweepDeduplicator.start(SweepDeduplicator.java:65)
        at org.eclipse.californium.core.network.Matcher.start(Matcher.java:139)
        at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:315)
        at org.eclipse.californium.core.CoapServer.start(CoapServer.java:200)

## when i start coapserver secend time and setExecutor to coapserver  then exception like this:

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@22616350 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@38a0bf9f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)[:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)[:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)[:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)[:1.8.0_161]
        at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)[:1.8.0_161]
        at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:154)
        at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.access$100(SweepDeduplicator.java:104)
        at org.eclipse.californium.core.network.deduplication.SweepDeduplicator.start(SweepDeduplicator.java:65
        at org.eclipse.californium.core.network.Matcher.start(Matcher.java:139)
        at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:315)
        at org.eclipse.californium.core.CoapServer.start(CoapServer.java:200)

**Comment by sbernard31** [comment]
Which version of californium are you using ?
Using branch 2.0.x, I tried  to start(), stop() and start() again and no exception raised on my side.
Could you share a snippet of code which could help to reproduce.

**Comment by xuzhiweiand** [comment]
I find the reason if you start and stop like this，error will happen。

    public static void main(String[] args) {
        try {
            Thread.currentThread().setDaemon(true);
            HelloWorldServer server = new HelloWorldServer();
            server.addEndpoints();
            server.start();
            server.stop();
            server.start();
        } catch (SocketException e) {
            System.err.println("Failed to initialize server: " + e.getMessage());
        }
    }

Exception in thread "main" java.lang.IllegalThreadStateException
	at java.lang.Thread.setDaemon(Thread.java:1359)
	at org.eclipse.californium.examples.HelloWorldServer.main(HelloWorldServer.java:41)

**Comment by boaks** [comment]
I'm a little mixed up.

Yes, your snippet throws a  `java.lang.IllegalThreadStateException `in line `Thread.currentThread().setDaemon(true);`. But that's the line you added, and I don't see the relation to californium. 

```
public class Simple {
	public static void main(String[] args) {
		Thread.currentThread().setDaemon(true);
	}
}
```

That causes the same exception even out of californium! 
So, why do you think, that  is an issue of californium?

**Comment by boaks** [comment]
Feel free to add a new comment or create a new issue, if you think this is related to californium.
