### ISSUE TITLE
DTLSConnector seems not able to handle fragment ClientHello handshake

### ISSUE THREAD

**Issue by minglight** [eclipse/californium#722]
# Please providing basic issue information
I use libcoap to send a DTLS request, and it throws an exception from the DTLSConnector on the ClinetHello handshake, it only happens when the ClientHello is split into fragments.

Here is the error stack
```
java.lang.ClassCastException: org.eclipse.californium.scandium.dtls.FragmentedHandshakeMessage cannot be cast to org.eclipse.californium.scandium.dtls.ClientHello
	at com.ayla.coapservice.customelement.DTLSConnector.processHandshakeRecordWithoutConnection(DTLSConnector.java:792)
	at com.ayla.coapservice.customelement.DTLSConnector.processHandshakeRecord(DTLSConnector.java:767)
	at com.ayla.coapservice.customelement.DTLSConnector.processRecord(DTLSConnector.java:508)
	at com.ayla.coapservice.customelement.DTLSConnector.access$200(DTLSConnector.java:90)
	at com.ayla.coapservice.customelement.DTLSConnector$2.run(DTLSConnector.java:474)
	at eu.javaspecialists.tjsn.concurrency.stripedexecutor.StripedExecutorService$SerialExecutor$1.run(StripedExecutorService.java:460)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And this is the wireshark dump file 
[jre.cap.zip](https://github.com/eclipse/californium/files/2293466/jre.cap.zip)

**Comment by boaks** [comment]
Scandium/californium seems not to be able to work with fragmented CLIENT_HELLOs.
Though I'm currently work on a larger redesign of scandium, I'm not able to fix this in the next days ;-(.

If possible, try to fix it on the client side in the meantime.
You may therefore either enlarge the used client message size (from about 300 to 500?), or you may reduce the size of the CLIENT_HELLO. In your case the CLIENT_HELLO lists 79 cipher suites, but only a few are supported by scandium. Therefore configure the the client dtls library to use only the ones, your really interested in.
For scandium only 

```
TLS_PSK_WITH_AES_128_CBC_SHA256(0x00AE)
TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256(0xC037)
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256(0xC023),
TLS_PSK_WITH_AES_128_CCM_8(0xC0A8)),
TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8(0xC0AE);

```
are supported.

**Comment by boaks** [comment]
I checked the code, to fix that seems to be hard. 
The current implementation prevents using state until the client has passed the cookie verification (see https://tools.ietf.org/html/rfc6347#section-4.2.1). 
So fixing it, would introduce state to accumulate the fragments before the client has proven it's address. And FMPOV, it' doesn't make too much sense to use that large numbers of (even unsupported) cipher suites.

So, could you limit the size of your CLIENT_HELLO by reducing the preferred cipher suites in the CLIENT_HELLO? The large set seems to be a "unlucky" examples set :-).

Or do you have a use-case for the large number of cipher suites?
