### ISSUE TITLE
Thread Leakage

### ISSUE THREAD

**Issue by nkitiyakara** [eclipse/californium#832]
Using 2.0.0-M11, I managed to achieve an "OutOfMemoryError: unable to create new native thread" error (full stack trace below) after making CoAP requests at one minute intervals for about 14 hours.   Granted that I was also creating a new client for every request, which definitely exacerbated the problem, but I think there is a thread leak even without that.  It's particularly pronounced when using the DTLSConnector, but it happens to a lesser extent with the UDPConnector.

An example is provided in the attached zip file:

[ScandiumThreadingProblem.zip](https://github.com/eclipse/californium/files/2703251/ScandiumThreadingProblem.zip)

One client using the UDPConnector reaches a maximum of 16 threads over 1000 get requests and goes down to 13 after the client and the server are stopped.  One client using the DTLSConnector reaches a maximum of 112 thread, dropping back to 61 (not counting the thread I'm using the check the number of active threads after the CoAP components are stopped).  Using 100 clients, the UDPConnector goes to 412 threads and drops back to 409, while the DTLSConnector goes to 5260 threads and drops back to 5209.  In all cases, I watched the number of threads for several minutes after stopping the CoAP components and did not see them start to drop back down.  (See attached *.txt files.)

I can mitigate this problem for now by reusing my clients instead of creating a new one for each request, but there are times that we'll legitimately want to stop using a particular client and it's unreasonable for it to not release all the threads it's created.

java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:231)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.access$000(SweepDeduplicator.java:168)
	at org.eclipse.californium.core.network.deduplication.SweepDeduplicator.start(SweepDeduplicator.java:115)
	at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.start(InMemoryMessageExchangeStore.java:385)
	at org.eclipse.californium.core.network.BaseMatcher.start(BaseMatcher.java:142)
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:475)
	at org.eclipse.californium.core.CoapClient.setEndpoint(CoapClient.java:341)
	at com.connectder.units.controllers.CoapUnitController.getCoapClient(CoapUnitController.java:60)
	at com.connectder.units.controllers.CoapUnitController.getSampleDataJson(CoapUnitController.java:67)
	at com.connectder.units.controllers.AbstractPollingUnitController.getSampleDataPayload(AbstractPollingUnitController.java:60)
	at com.connectder.units.controllers.AbstractPollingUnitController.publishSampleData(AbstractPollingUnitController.java:52)
	at com.connectder.units.controllers.AbstractPollingUnitController.executeTimedProcesses(AbstractPollingUnitController.java:48)
	at com.connectder.commands.ExecutePollingActionJob.executeUnitAction(ExecutePollingActionJob.java:35)
	at com.connectder.commands.UnitCommandProcessorJobBase.executeAction(UnitCommandProcessorJobBase.java:48)
	at com.connectder.commands.CommandProcessorJobBase.run(CommandProcessorJobBase.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[dtlsconnector_1_client.txt](https://github.com/eclipse/californium/files/2703273/dtlsconnector_1_client.txt)
[udpconnector_100_client.txt](https://github.com/eclipse/californium/files/2703274/udpconnector_100_client.txt)
[udpconnector_10_client.txt](https://github.com/eclipse/californium/files/2703275/udpconnector_10_client.txt)
[udpconnector_1_client.txt](https://github.com/eclipse/californium/files/2703276/udpconnector_1_client.txt)
[dtlsconnector_100_client.txt](https://github.com/eclipse/californium/files/2703277/dtlsconnector_100_client.txt)
[dtlsconnector_10_client.txt](https://github.com/eclipse/californium/files/2703278/dtlsconnector_10_client.txt)

**Comment by boaks** [comment]
Any reason, why you use 2.0.0-M11 instead of M12?

The `CoapClient.setEndpoint()` has some javadoc, did you read that?

```
	/**
	 * Sets the endpoint this client is supposed to use.
	 * 
	 * The endpoint maybe shared among clients. Therefore {@link #shutdown()}
	 * doesn't close nor destroy it.
	 *
	 * @param endpoint the endpoint
	 * @return the CoAP client
	 */
```

I would guess, that if you destroy the CoapEndpoints, when you don't longer use them, your issue should get smaller. I'm not sure, when (or even if :-) ) your GC may collect the Threads, but that seems to be nondeterministic.

**Comment by nkitiyakara** [comment]
Destroying the endpoints when I'm done with the client does the trick all right.  In my model application, all the client & server threads went away within a minute or so after destroying the endpoints.  I'd been focused on getting the communications encrypted and hand't even looked at the setEndpoint javadoc beyond that it took an Endpoint.  I'm still a little disturbed that 100 clients uses more than 5,000 threads, but that just means running the clients on multiple computers at the worst.  (The Linux server I was running it on topped out at around 32k threads.)

Re: M11 v. M12 - This project had been shelved for a while and I just didn't check for a new release when it restarted.  I'll likely see about upgrading after the holidays.

Thanks for your help.
